### ISSUE TITLE
Task is not adding work items to PR

### ISSUE THREAD

**Issue by mdverde** [shayki5/azure-devops-create-pr-task#100]
We have some pipelines to automate the creation of PRs, but for some reason some of them are not linking the work items even tough the setting is enabled on the task and the source commits have one or more linked work items:

![image](https://user-images.githubusercontent.com/18468967/118015867-fb7cad00-b311-11eb-8019-ec6a181014c4.png)

![image](https://user-images.githubusercontent.com/18468967/118015965-151df480-b312-11eb-9faf-0ee3cd2cb687.png)

Because of branch policies, every commit must have linked work items, and I always double check that's the case when this issue happens.

Am I missing something? Is it a bug?

Thanks!

**Comment by shayki5** [comment]
Hi,
Can you run the pipeline with the variable `system.debug` = `true` and share here the logs?
Thanks!

**Comment by shayki5** [comment]
@mdverde ping :)

**Comment by mdverde** [comment]
Hi, sorry for not responding. Can we reopen this?

The task is working fine in other pipelines, but for one specific is failing to add the work items to the PR. The main difference is that the code repository is on a different project than the work items.

Last test I did was to move the pipeline from the project containing the code repo to the project containing the work items, but it's still not attaching the work items.

Logs attached with replaced Ids.

[pipeline.log](https://github.com/shayki5/azure-devops-create-pr-task/files/6964519/pipeline.log)

Thank you!

**Comment by shayki5** [comment]
Hi, I re-opened :)
I tried it in my organization and I get the work items even from another project. 
I added more debug prints, can you run it again and share the logs?

**Comment by mdverde** [comment]
Thank you. I ran it again, but I don't see any change on the logs. Should I do anything to make sure it gets the latest version?

**Comment by shayki5** [comment]
It should be updated it automatically. 
Which version do you see in the logs?
And, did you run it `system.debug` = `true`?

**Comment by mdverde** [comment]
it's getting version 1.2.257, so it should be fine, but I don't see any change on the debug logs. This is the latest run:

[pipeline.log](https://github.com/shayki5/azure-devops-create-pr-task/files/6969003/pipeline.log)

**Comment by shayki5** [comment]
Yes, 257 is the latest.
So, it looks like the work items not linked to the PR changes, see in my case:
![image](https://user-images.githubusercontent.com/26063853/129044807-5e13b7d8-cadc-4b00-9fc2-1b42d2bbe676.png)

**Comment by mdverde** [comment]
We will perform a new set of controlled tests, because on previous scenarios, I'm sure that at least one commit has at least one linked work item.

Thank you.

**Comment by shayki5** [comment]
Very strange!
If you want you can give me read access and I will check it :)
