### ISSUE TITLE
hold the stage until PR approved and complete

### ISSUE THREAD

**Issue by manojsharma0387** [shayki5/azure-devops-create-pr-task#104]
Hi Team, Is it possible to hold the stage until PR is fully approved and complete. Because what is happening if I am passing required reviewer, the Pull request is getting raised but waiting for approver to complete and stage is showing successfully completed. Is it possible to hold the stage until PR fully approved.

**Comment by shayki5** [comment]
Do you mean to hold the pipeline stage? I don't think it's possible.

**Comment by manojsharma0387** [comment]
thank you

**Comment by shayki5** [comment]
What you can do, is to add a PowerShell task that check the PR status every 1 minuets and only if it merged to continue next steps. but you need to increase the pipeline timeout.

**Comment by manojsharma0387** [comment]
But PR ID need to supply to PS task, that ID we can add as an variable in pipeline

**Comment by shayki5** [comment]
You can set the `passPullRequestIdBackToADO:` to `true` and then use the variable `$(pullRequestId)`.
