### ISSUE TITLE
Trying to run on non-windows vm

### ISSUE THREAD

**Issue by tcukanoot** [shayki5/azure-devops-create-pr-task#108]
Any thoughts on, or workarounds for, getting this to work on non-windows?
  vmImage: 'ubuntu-latest'

Thank you

**Comment by shayki5** [comment]
Hi, unfortunately no 😕, see issue #22.
You can just add PowerShell step (should work in Linux as well) and put the PS script that create the PR, you can copy the code from this task. 
**For example:** (see [here](https://stackoverflow.com/questions/56184170/ci-cd-pipelines-azure-devops-automatic-merge-after-deploy-release/56211646#56211646)) 
```
$body =  @{
             sourceRefName= "$(Build.SourceBranch)"
             targetRefName = "refs/heads/master"
             title = "PR from Pipeline"
     }

$head = @{ Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"  }
$json = ConvertTo-Json $body
$url = "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.Name)/pullrequests?api-version=5.0"
Invoke-RestMethod -Uri $url -Method Post -Headers $head -Body $json -ContentType application/json
```
