### ISSUE TITLE
Enhancement: Make PR title more dynamic as existing code supports multi target branches

### ISSUE THREAD

**Issue by praveenkumar510** [shayki5/azure-devops-create-pr-task#110]
Before requesting this enhancement, This extension is very useful and working robust! To provide more features , I would like to request dynamic title support for PR. Please let me know if you allow me to be a contributor. Thanks!

**Comment by shayki5** [comment]
Hi @praveenkumar510,
Sure! You can contribute! 
But, the title is dynamic, you can refer to the target branch name with `[BRANCH_NAME]`:
![image](https://user-images.githubusercontent.com/26063853/128980143-f2009e27-44e1-42c0-9c08-78247af08fb2.png)

**Comment by praveenkumar510** [comment]
Found the code. Thank you!

$pullRequestTitle = $title.Replace('[BRANCH_NAME]', $branch.Replace('refs/heads/',''))
