### ISSUE TITLE
[error]The underlying connection was closed

### ISSUE THREAD

**Issue by GrumpyVader** [shayki5/azure-devops-create-pr-task#112]
I'm using the Azure DevOps repository type with Current Repository build. I set the branch to test/* and defined a custom Title for testing. No other options are set. 

I also tried Selecting the Project and Repository and specifying the Source branch.

When I run the release, the PR step throws the following error.

##[error]The underlying connection was closed: An unexpected error occurred on a receive.

**Comment by shayki5** [comment]
Hi, can you run it with `system.debug` = `true` and share here the logs?

**Comment by GrumpyVader** [comment]
I apologize for such a long delay. I finally got back to trying this and I have the debug info. Let me know if there is anything else I can get you.

[CreatePullRequest-ErrorLog.txt](https://github.com/shayki5/azure-devops-create-pr-task/files/7189028/CreatePullRequest-ErrorLog.txt)

**Comment by shayki5** [comment]
Hi, the master and target are the same, can you change it?
Are you behind a proxy?
