### ISSUE TITLE
Reviewers can not be found

### ISSUE THREAD

**Issue by FabianHegg** [shayki5/azure-devops-create-pr-task#117]
It seems like the task finds the right team, but can not fill in the right id (see logs below). While having a look at the code, i found  a mysterious variable $u (see linked line). Is this the bug, which causes this issue?

2021-11-09T06:40:41.5184281Z     "reviewers":  [
2021-11-09T06:40:41.5184873Z                       {
2021-11-09T06:40:41.5185547Z                           "id":  "",
2021-11-09T06:40:41.5186315Z                           "isRequired":  "false"
2021-11-09T06:40:41.5187785Z                       }
2021-11-09T06:40:41.5188353Z                   ],

https://github.com/shayki5/azure-devops-create-pr-task/blob/5d37bd528090d48a6638586f227b6b25295175d8/task/createPullRequest.ps1#L516

**Comment by FabianHegg** [comment]
Thank you@shayki5! Do you already know, when the fix will be released?

**Comment by shayki5** [comment]
Hi @FabianHegg,
Thank you! look like a bug!
I fixed it now, can you try again? (verify you are using the new version: 1.2.259)

**Comment by FabianHegg** [comment]
@shayki5 Yes, i will have to let it install on our Azure DevOps Server instance. I will give you feedback as soon as i can.

**Comment by shayki5** [comment]
Great, thank you!

**Comment by shayki5** [comment]
@FabianHegg did you manage to test it?

**Comment by Shaindy1** [comment]
Hi @shayki5,
I got the same error when I try to add specific user to reviewer: the task finds the user but not but can not fill in the right id
so I want to use to assign a team reviewer but I not found the 1.2.259 release to update my extension, the latest is 213.
How can I get it?

**Comment by shayki5** [comment]
@Shaindy1 just download it from here:
https://marketplace.visualstudio.com/items?itemName=ShaykiAbramczyk.CreatePullRequest -> "Get it free"

**Comment by Shaindy1** [comment]
> @Shaindy1 just install or download it from here: https://marketplace.visualstudio.com/items?itemName=ShaykiAbramczyk.CreatePullRequest -> "Get it free"

I'll try, thanks!

**Comment by FabianHegg** [comment]
> @FabianHegg did you manage to test it?

@shayki5 Not yet. It got installed today. We will test it during release next tuesday. I will write the results here.

**Comment by Shaindy1** [comment]
@shayki5  After updating the version, user reviewer and team reviewer work for me!!! 
Thanks!

**Comment by FabianHegg** [comment]
@shayki5 It works for us now. Thanks a lot!

**Comment by shayki5** [comment]
@FabianHegg Awesome! 
Thanks for finding the bug!
