### ISSUE TITLE
Feature Request: Only create PR if there are no file changes

### ISSUE THREAD

**Issue by sgabler** [shayki5/azure-devops-create-pr-task#118]
This is more of a feature request, and I would be happy to assist in the implementation if you think this is a good idea.

**Would it be possible to provide an option "Ignore merge commits" or something like that to avoid empty PRs?**

Here is how the PR currently gets created for us:

![image](https://user-images.githubusercontent.com/3625477/141339004-9f54795b-8a05-43ad-9b2d-7fefe385ed5a.png)

But the file diff looks is empty:

![image](https://user-images.githubusercontent.com/3625477/141339368-bc5de113-5362-43bb-93ab-882e0a965593.png)

I understand that on the git level the difference between the two branches are those 4 commits, but in our current workflow, this would not be so ideal. We are following some version of gitflow, where you create a PR from release branch into master if you want to do a deployment. We basically want to automate the case that, after a hotfix into the master branch, a PR is created to automatically merge back the changes from master into release.

I already checked the code and it seems to me that the method `CheckIfThereAreChanges` would be a good place to start.

Please let me know what you think about this 🙂

**Comment by shayki5** [comment]
Hi,
Yes, it's a good idea :)
Juts need to think how to determine when the diff is really empty.
I can take a look when I will have a time, if you can contribute if would be great :)

**Comment by sgabler** [comment]
Thank you! I just took a look and I think I found one possible solution already:

In the method `CheckIfThereAreChanges` the following line is executed:
```
    $url = "$env:System_TeamFoundationCollectionUri$($teamProject)/_apis/git/repositories/$($repositoryName)/diffs/commits?baseVersion=$($sourceBranch)&targetVersion=$($targetBranch)&api-version=4.0" + '&$top=2'
```

This gives me something like this:

```json
{
    "allChangesIncluded": true,
    "changeCounts": {},
    "changes": [],
    "commonCommit": "5b1573c9a01a78d81bb2cf6cfae40676b7efb436",
    "baseCommit": "4866ecdede7ab4f2144035bc101a584855e862c0",
    "targetCommit": "b0f4953657ed3f3541d9953ec4b77baf24d72a8e",
    "aheadCount": 4,
    "behindCount": 2
}
```

If you add another query parameter `&diffCommonCommit=false`, then the response changes to this (i replaced the sensitive info with `<replaced>`):

```json
{
    "allChangesIncluded": true,
    "changeCounts":
    {
        "Edit": 3
    },
    "changes":
    [
        {
            "item":
            {
                "objectId": "07c1cd6a0a33b47c1fa28458367d3d0f609eae21",
                "originalObjectId": "a9f4b24f05baad11609ac8fce76a94d340b43b86",
                "gitObjectType": "tree",
                "commitId": "b0f4953657ed3f3541d9953ec4b77baf24d72a8e",
                "path": "<removed>",
                "isFolder": true,
                "url": "<removed>"
            },
            "changeType": "edit"
        },
        {
            "item":
            {
                "objectId": "bed9fe4914878ababbff4745156a3114c5b895d8",
                "originalObjectId": "c2610c14dbe392c553f6d236602bf3c87dc16db2",
                "gitObjectType": "tree",
                "commitId": "b0f4953657ed3f3541d9953ec4b77baf24d72a8e",
                "path": "<removed>",
                "isFolder": true,
                "url": "<removed>"
            },
            "changeType": "edit"
        },
        {
            "item":
            {
                "objectId": "8c9a39a00f6be600ba0dbed05532bc9aa6985a1d",
                "originalObjectId": "a5a8ae72c7a2342b76d7f33042dff3376021f3a3",
                "gitObjectType": "blob",
                "commitId": "b0f4953657ed3f3541d9953ec4b77baf24d72a8e",
                "path": "<removed>",
                "url": "<removed>"
            },
            "changeType": "edit"
        }
    ],
    "commonCommit": "5b1573c9a01a78d81bb2cf6cfae40676b7efb436",
    "baseCommit": "4866ecdede7ab4f2144035bc101a584855e862c0",
    "targetCommit": "b0f4953657ed3f3541d9953ec4b77baf24d72a8e",
    "aheadCount": 4,
    "behindCount": 2
}
```

I think we could use the `changeCounts` property of the response.

I quickly tested what happens if there are only commit changes, but not file changes. In that case the `changeCounts` will be `{}`. Same happens if you compare the branch to itself, so no commit or file changes.

So the basic logic could be:

```
If the `changeCounts` object is an empty object
    Don't create PR
else
    Create PR
```

What do you think?

**Comment by shayki5** [comment]
We can try it. here:
```  
if ($response.behindCount -eq 0) {
```
We need to replace the `behindCount` with `changeCounts`.
Do you want to open a PR? if not I can do it :)

**Comment by sgabler** [comment]
> Do you want to open a PR? if not I can do it :)

I would appreciate if you could do it, as i have not set anything up to test it yet and I imagine that testing this could be a bit tricky.

But if you are short on time, let me know, then I will try it :)

**Comment by shayki5** [comment]
Hi @sgabler,
I tried to fix it by check also the `changeCounts`. 
Can you check if it solved your scenario? (check your extension version is 1.2.160)

**Comment by sgabler** [comment]
Thank you for the fast implementation. I will test it now, but based on my above research I would assume that you also need to append the `&diffCommonCommit=false` to the URL, otherwise the `changeCounts` object is always empty. At least that's how it behaved for me. Here' a link to the documentation: [link](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/diffs/get?view=azure-devops-rest-4.1)

I will let you know shortly if it works, but I already really appreciate the fast response

**Comment by sgabler** [comment]
I double checked to use the right version 1.2.160, and an empty PR was still created

![image](https://user-images.githubusercontent.com/3625477/141959172-18a1ba1b-e2e3-4ecf-aa46-4934add8ff61.png)

It will probably work if you append the query parameter `&diffCommonCommit=false`. Apart from that the rest of the response looks the same, so I think it's safe to do it

here's a diff between the two responses: left without query parameter, right with query parameter

![image](https://user-images.githubusercontent.com/3625477/141959415-7d9d02cd-799a-4596-a345-1ca50591dda3.png)

**Comment by shayki5** [comment]
Oh I forgot it! I added it, can you check now?

**Comment by sgabler** [comment]
```
Task         : Create Pull Request
Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
Version      : 1.2.261
Author       : Shayki Abramczyk
Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
==============================================================================
The repository is: 0baf6bfa-ffa8-4b34-9293-cf7462fbd850
The Source Branch is: refs/heads/master
The Target Branch is: refs/heads/release
The Title is: 🤖 Merge master into release
The Description is: Automatically created by "Azure DevOps Create Pull Request Task"
Is Reviewers are: 
Is Draft Pull Request: False
Auto-Complete: True
Link Work Items: True
Bypass: False
Bypass Reason: 
6 new commits! perform a Pull Request...
{
    "forkSource":  "",
    "sourceRefName":  "refs/heads/master",
    "title":  "🤖 Merge master into release",
    "WorkItemRefs":  [
                         null
                     ],
    "description":  "Automatically created by \"Azure DevOps Create Pull Request Task\"",
    "reviewers":  "",
    "isDraft":  "False",
    "targetRefName":  "refs/heads/release"
}
*************************
******** Success ********
*************************
Pull Request 3084 created.
```

It still didn't work. I think it's because the comparison should be different.

You are using `$response.changeCounts -eq 0`, but that probably requires a number. But in our case, the `"changeCounts": {},` returns an empty javascript object, not a number.

I checked the docs here: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.2

Is it possible to write `$response.changeCounts -eq "{}"` or is there a better way?

We're almost there ;)

**Comment by shayki5** [comment]
I think I fixed it :) can you try again?

**Comment by sgabler** [comment]
thank you! it worked 🎊 

tested cases:
- only commit diffs, but no file changes => no PR should be created ✅ 
- commit diffs with file changes => PR should be created ✅ 

very nice 🙂 

only thing I noticed was the message `There are no new commits in the source branch, no PR is needed!`, which is not strictly true anymore. Maybe it could be changed to `There are no new changes in the source branch, no PR is needed!`?

**Comment by shayki5** [comment]
Great!!
Good idea about the message, I changed it to `changes` :)
Thank you for all your comments!
