### ISSUE TITLE
Can't Bypass Policy if Set Auto Complete is true

### ISSUE THREAD

**Issue by mwazzangrg** [shayki5/azure-devops-create-pr-task#119]
Hi team, this is a great plugin!

I'm having an issue with Bypass Policy and Set Auto Complete

Basically I need to tick both. The problem is that when I tick Set Auto Complete box, Bypass Policy box disappears.

Is this a bug or by design?

What I need is to bypass the policy, complete the PR and delete the original branch.

**Comment by shayki5** [comment]
Hi! It's by design, when you choose "Bypass" it's auto complete the PR and bypass the policies.
I don't know what happened to the source branch, need to check.

**Comment by mwazzangrg** [comment]
Thanks Shayki

**Comment by shayki5** [comment]
@mwazzangrg try click on "Auto complete" check the "Delete source branch" and then click on "Bypass", maybe it will save the configuration and will delete the branch. can you check?
