### ISSUE TITLE
Switch to TLS 1.2

### ISSUE THREAD

**Issue by kyletanders** [shayki5/azure-devops-create-pr-task#123]
Invoke-RestMethod by default uses TLS 1.0 which is not secure.  At my company we have TLS 1.0 disabled for security reasons, so I cannot use this package.  

I think switching to TLS 1.2 is a fairly simple change in the powershell script.  Just need to add something like the below:
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

**Comment by shayki5** [comment]
Hi @kyletanders, I updated the code, can you check it works for you?

**Comment by kyletanders** [comment]
Seems to work now.  Thanks!
