### ISSUE TITLE
Version 1.2.278 saying no changes when there are

### ISSUE THREAD

**Issue by ccicrlucas** [shayki5/azure-devops-create-pr-task#127]
![image](https://user-images.githubusercontent.com/67339044/145286275-f08ee72e-5d3d-4bcc-ab69-a316ea33455c.png)

However, I was able to manually create a PR for the branch in question to develop branch. Verbose doesn't add much insight.

![image](https://user-images.githubusercontent.com/67339044/145289368-a5da51c1-9821-4a3e-b5ff-617b8e1f67aa.png)
File changes exist from branch -> develop

![image](https://user-images.githubusercontent.com/67339044/145289312-8f888f97-ff70-4550-95ac-6f01d3395105.png)
Tried running the api call you make here: https://github.com/shayki5/azure-devops-create-pr-task/blob/master/task/createPullRequest.ps1#L454 - and I think there's an issue with this logic. Introduced here:

![image](https://user-images.githubusercontent.com/67339044/145290149-bec4a080-74b0-4578-b87d-9d9c775abe39.png)
https://github.com/shayki5/azure-devops-create-pr-task/commit/99d8d297156be0a25288aea87bad20f354fcf130#diff-95196cf85a5fcd80c9fd6b240af99229cea2be22a3e7b74329944a4cd20728f9R454

I'll be tagging a PR for this issue.

Thanks!

**Comment by ccicrlucas** [comment]
https://github.com/shayki5/azure-devops-create-pr-task/pull/128 - please review to resolve.

**Comment by shayki5** [comment]
Hi! thanks for reporting!
I think it because of https://github.com/shayki5/azure-devops-create-pr-task/commit/ed4be96024f0ebab79aeebd2ad892f1d90e8fac6.
I did it without testing, now I can reproduce your issue in my side.
I reverted it. can you try in 5 mins.?

**Comment by rdlucas2** [comment]
PR still not creating. I did pick up the new version. (Posting from another account 🙂)

Error is now: There are no new changes in the source branch, no PR is needed!

**Comment by agitnaeta** [comment]
PR Still said there is no change. 
There is anyone try to resolve it?

**Comment by shayki5** [comment]
Hi, I’m sorry about it! I will solve it in ~2 hours.

**Comment by shayki5** [comment]
@ccicrlucas  @rdlucas2 @agitnaeta solved 😀 I'm sorry for the trouble!

**Comment by rdlucas2** [comment]
Hey, no need to apologize. It works again, marking resolved! Thanks!

**Comment by shayki5** [comment]
@ccicrlucas @agitnaeta can you verify it works for you now?

**Comment by ccicrlucas** [comment]
> @ccicrlucas @agitnaeta can you verify it works for you now?

Yes - again, thank you. I've closed the issue as well. Thanks for your responsiveness!
