### ISSUE TITLE
Error for GitHub PR

### ISSUE THREAD

**Issue by Leafrostar** [shayki5/azure-devops-create-pr-task#13]
I tried this task for GitHub PR and facing below error, do you have any idea?

##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

**Comment by shayki5** [comment]
Hi @Leafrostar,
Thank you for trying the task :)
Do you use Windows or Linux?

**Comment by Leafrostar** [comment]
I am using Windows

**Comment by shayki5** [comment]
Is is Self hosted agent, right? If you login to the machine with the user that the build use, can you open PowerShell and run scripts?
Which Windows version is?

**Comment by Leafrostar** [comment]
I am not sure whether is Self hosted agent, will figure it out. 
I can open PowerShell and run scripts (cannot run as administrator)
Windows version is Windows 10 Enterprise

**Comment by Leafrostar** [comment]
I found this in the jobs log:

Pool: Azure Pipelines
Image: ubuntu-latest

So that means it's Microsoft hosted agent and is Linux VM.
That's why I face this error.

**Comment by shayki5** [comment]
@Leafrostar exactly.
Try to change the pool to `windows-latest`.

**Comment by Leafrostar** [comment]
Now I am facing:

##[error]{"message":"Draft pull requests are not supported in this repository.","documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}

I didn't check "Create Draft Pull Request"

**Comment by shayki5** [comment]
Can you run the pipeline with the variable `system.debug` = `true` and share here the full log of the task?

**Comment by Leafrostar** [comment]
[log.txt](https://github.com/shayki5/azure-devops-create-pr-task/files/3921092/log.txt)

**Comment by shayki5** [comment]
Thank you!
You repo is a public repo or a private repo?

**Comment by Leafrostar** [comment]
It's private repo

**Comment by shayki5** [comment]
Ok, private repos support draft pull request only with GitHub Team and GitHub Enterprise Cloud and I send `draft=false` so it fails.
I fix it now and I will update you soon :)

**Comment by Leafrostar** [comment]
Thank you!

**Comment by shayki5** [comment]
I fixed it :)  - the new version is 1.2.41
Please try to run it now and check if it works.

**Comment by Leafrostar** [comment]
It's working now. Thank you for the fast response and fix.
