### ISSUE TITLE
You need the Git 'GenericContribute' permission

### ISSUE THREAD

**Issue by saibharath005** [shayki5/azure-devops-create-pr-task#130]
Hi Shayki Abramczyk,

Sorry for the review but I am facing the below issue, Can you please help me out.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/66404638/147490360-a6183f11-3c43-4b82-846f-eea11c371ee5.png">

If we need any call or working session i will be available to join. Please Help me out.

**Comment by shayki5** [comment]
Hi, you need to give permissions as in the picture (to both users):
![image](https://user-images.githubusercontent.com/26063853/147542913-6c2dd467-3761-4aee-b39c-59c1933fda14.png)

**Comment by saibharath005** [comment]
HI @shayki5 ,

Can you please help me with how to add these two users in my Azure Devops account please.

**Comment by shayki5** [comment]
Sure, send a Zoom link.

**Comment by saibharath005** [comment]
HI @shayki5,

I have joined the bridge, 
https://us04web.zoom.us/j/79715962341?pwd=akxicWIwYkVBTjZEK1JGcFBXUHV6UT09

**Comment by saibharath005** [comment]
HI @shayki5,

I have joined the bridge,
Sai Bharath Kothakota is inviting you to a scheduled Zoom meeting.

Topic: Sai Bharath Kothakota's Zoom Meeting
Time: Dec 29, 2021 04:00 PM India

Join Zoom Meeting
https://us04web.zoom.us/j/76088061355?pwd=aGVRZy8xakpSQm1UZEkzWTR3dEZsQT09

Meeting ID: 760 8806 1355
Passcode: rmrX1y

**Comment by saibharath005** [comment]
Thank You So Much @shayki5.

In the Users section for the org user i have allowed the access then my issue got fixed.
