### ISSUE TITLE
Add support for tags

### ISSUE THREAD

**Issue by pnwguy** [shayki5/azure-devops-create-pr-task#131]
Enhancement request - when creating a pull request, add optional tags/labels.

**Comment by mario-santos-solytic** [comment]
We use tags to skip to build and test Tasks, so it would be nice that, when creating some automated PR via this Tool, we could add some tags that to speed up the workflow and save some resources (agents)

**Comment by SteffenMangold** [comment]
Supporting this +1

**Comment by shayki5** [comment]
Hi @pnwguy and @SteffenMangold,
Now it's possible :)
Use `tags: tag1;tag2` in the yaml.
