### ISSUE TITLE
Link to existing work item?

### ISSUE THREAD

**Issue by bobnotbob** [shayki5/azure-devops-create-pr-task#138]
Hi, in my release pipeline, I'm creating a work item and getting back the Id.  Is it possible to then create a pull request using your task, and link it to that work item?  Thanks.

**Comment by bobnotbob** [comment]
Sorry, I just saw that's already been requested as an enhancement.

**Comment by shayki5** [comment]
@bobnotbob Yea... I closing that issue. I see there is a demand so I hope to add it soon!!

**Comment by shayki5** [comment]
Duplicate of #84
