### ISSUE TITLE
GitHub Merge after Create PR

### ISSUE THREAD

**Issue by Leafrostar** [shayki5/azure-devops-create-pr-task#14]
Currently for GitHub, it can only create PR without merge PR ?
Is any way to merge PR also?

**Comment by shayki5** [comment]
Hi,
Do you mean to create a PR and immediately merge the branches? if yes, so you can do just merge, for what do you need the PR?

**Comment by Leafrostar** [comment]
Yes exactly. I need to create and merge the PR regularly and automatically.

**Comment by shayki5** [comment]
If you do not use the power of the PR (code review, builds check, etc.) so why to use PRs? you can do `git merge` between the branches. no?
In second thought, maybe you use PR but sometimes you need to perform the auto-merge?

**Comment by Leafrostar** [comment]
My intention is to use Azure pipeline tasks to do `git merge` on GitHub automatically.
But for GitHub actions in Azure pipeline I think cannot do `git merge` directly, need some tasks like the one you provided.

**Comment by shayki5** [comment]
If the branch is "locked" and force a Pull Request you can't do `git merge`, but if not you can add a command-line task that perform the `git merge`.
Anyway, I will start work on it and I will add this feature soon :)

**Comment by Leafrostar** [comment]
Thank you for the info! Let me have a try on using command-line task to preform `git merge` for GitHub

**Comment by shayki5** [comment]
You'ew welcome!
You need to `cd` to the repo folder, then perform the merge. don't forget to authenticate with PAT.
But again, if your repo settings require PR you can't do it.

**Comment by Leafrostar** [comment]
Thanks for the details. It makes me knowing what to do.

**Comment by shayki5** [comment]
Hi @Leafrostar,
Did you try to do the merge?

**Comment by shayki5** [comment]
I close this issue, if this feature can help others please update here and I will add it.
