### ISSUE TITLE
Source from specific commit on branch

### ISSUE THREAD

**Issue by tcukanoot** [shayki5/azure-devops-create-pr-task#142]
There may be a delay or multiple days between when our pipeline starts, and when it ultimately completes by by generating the pull request. In that time, there may have been additional commits to the source branch, so when the pull request task runs, it's actually pulling in newer code than what started the pipeline.

Is there a way to generate the pull request from the specific commit of the source branch? The one that was used to start the pipeline?
sourceBranch: '$(Build.SourceBranch)'

Thanks,

**Comment by shayki5** [comment]
Hi,
It's impossible due git limitation, a PR merging a whole branch into another.
You can create a new branch from the specific commit and create the PR from this branch.
