### ISSUE TITLE
The current operating system is not capable of running this task. (Ubuntu)

### ISSUE THREAD

**Issue by stephen-james-pe** [shayki5/azure-devops-create-pr-task#146]
I'm running hosted build agents running Ubuntu.

When trying to use this plugin I receive this error, 

Is there  work around?

##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

**Comment by shayki5** [comment]
Hi, the task working only in Windows agent 😕 see #22.
There is a PR to make is cross-platform: #145, but I need time to handle it..
As a workaround you can add a new job on windows pool and run it :)
