### ISSUE TITLE
Delete Source Branch yaml misspelled

### ISSUE THREAD

**Issue by tcukanoot** [shayki5/azure-devops-create-pr-task#147]
Using the GUI editor in yaml pipelines, checking the 'Delete Source Branch' box results in a misspelled attribute in the yaml:
deleteSourch: true

![image](https://user-images.githubusercontent.com/37633617/185433963-cd427099-ac78-47d4-8bde-b419b73811e8.png)

**Comment by shayki5** [comment]
Hi, it's ok, it still should works, was typo in the first version and now both options should works :)
Can you check it please if it working for you?

**Comment by tcukanoot** [comment]
Looks good, thanks.
