### ISSUE TITLE
Page Not found error

### ISSUE THREAD

**Issue by sush25mita** [shayki5/azure-devops-create-pr-task#15]
Create Pull request task is showing Page not found error on selecting 'Set Auto Complete'. Pull request is being created but error in auto complete. I am using Azure DevOps.

*************************
Pull Request 440 created.
##[debug]'link'/_apis/graph/users?api-version=4.1-preview.1
##[debug]GET 'link'/_apis/graph/users?api-version=4.1-preview.1 with 0-byte payload
##[debug]Leaving RunTask.
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]CreateAzureDevOpsPullRequest : 
##[debug]
##[debug]  

##[debug]    Page not found.
##[debug]    html {

##[debug]    height: 100%;
##[debug]}
##[debug]
##[debug]body {
##[debug]    font-family: "-apple-system", BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Helvetica, Ubuntu, Arial, sans-serif, "Apple Color Emoji",
##[debug]        "Segoe UI Emoji", "Segoe UI Symbol";

**Comment by shayki5** [comment]
Hi @sush25mitam,
Can you share with me the `'link'` in the URL? just remove the organization name.
And just to verify, do you use Azure DevOps in the cloud, not Azure DevOps Server on-prem?

**Comment by sush25mita** [comment]
Hi shayki5

The issue is resolved. Resolution was to enable the use of new URL for organization in settings. As the function to get the builduserid was resulting to error due to wrong API. The environment variable $env:System_TeamFoundationCollectionUri was returning old URL which was leading to wrong API. 
Once we had enabled new URL the API was redirecting though new URL as 'dev.azure.com'.
Request you to just make the error output bit elaborative, as error 'page not found' leads too many confusion.  Thanks!!

**Comment by shayki5** [comment]
Thank you for the update!
I will update the docs with this information.
