### ISSUE TITLE
Does not work under Linux x64 agent

### ISSUE THREAD

**Issue by michalwitek1232** [shayki5/azure-devops-create-pr-task#152]
**More informations**
--------------------------------------
I was using self-hosted linux (Ubuntu 20) agent under x64 architecture

Error output: 
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

**Comment by shayki5** [comment]
Hi, yea, it's written in the docs, currently it working only on windows agent, see #22 and #145.
If you have one windows agent you can add a new job only for this task.
