### ISSUE TITLE
Getting 403 Forbidden in the CreatePullRequestTask

### ISSUE THREAD

**Issue by manjushm-microsoft** [shayki5/azure-devops-create-pr-task#154]
This is the link to the repo pipeline: https://office.visualstudio.com/OneNote/_build/results?buildId=17524458&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=fed80cdb-7c57-517c-0927-8cec0f1239ba&l=33

![image](https://user-images.githubusercontent.com/12942567/215905390-7082667a-c1e3-4d8c-99e6-a933786b4d4f.png)

And this is how the task is defined in the yml
![image](https://user-images.githubusercontent.com/12942567/215905601-ec04493b-6581-4379-9a9e-fa8f48c5b61b.png)

**Comment by shayki5** [comment]
Hi, can you run it with diagnostic logs and share here the full logs?
In addition, did you grant the permissions to the user according to the docs?
