### ISSUE TITLE
Set the creator of the PR to the author of the commit instead of the Build Service User

### ISSUE THREAD

**Issue by AndrewGene** [shayki5/azure-devops-create-pr-task#155]
Right now, it creates the PR with the author being the Build Service User.  For now, we are appending the author of the commit (the one who started the pipeline) into the description (their name and email) and adding them as an optional reviewer.  Is there a way to set them as the author of the PR instead? Thanks.

**Comment by shayki5** [comment]
Hi @AndrewGene, I think it's impossible:
https://developercommunity.visualstudio.com/t/changed-createdby-with-git-create-pull-request-api/459964
But I will do some tests..

**Comment by shayki5** [comment]
@AndrewGene I just tested it and it's impossible, I provided my id in the body but the PR still created with the default user:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/26063853/232869076-399b2e1c-78f1-44e2-b338-0108ff49c766.png">
See also this issue: https://github.com/Azure/azure-rest-api-specs/issues/10797
