### ISSUE TITLE
Wildcard support in targetBranch

### ISSUE THREAD

**Issue by inikulshin** [shayki5/azure-devops-create-pr-task#157]
Hi, Shayki,
ד"ש מ-Varonis :)

Wildcard support in targetBranch is limited (only works for single `*` in the end), wrong (`foobar` branch will match `*foo` pattern) and awkward.

I suggest to replace

```
if ($targetBranch.Contains('*')) {
...
        $targetBranches = ($refs.value.Where({ $_.name -match "$($targetBranch.Replace('*',''))" })).name
...
        $targetBranches = $branches.name.Where({ $_ -match "$($targetBranch.Replace('*',''))" })
}
```

with something like

```
if ([Management.Automation.WildcardPattern]::ContainsWildcardCharacters($targetBranch)) {
...
        $targetBranches = ($refs.value.Where({ $_.name -like $targetBranch })).name
...
        $targetBranches = $branches.name.Where({ $_.name -like $targetBranch })
}
```
### Update:
Oh, I continued to read:

This check must be done **before** wildcard and not **instead**
```
        elseif($targetBranch.Contains(';')) {
            $targetBranches = $targetBranch.Split(';')
        }
```
->
```
        $targetBranches = $targetBranch.Split(';') # will create array with single element even if no ';'
```

and when

```
if ([Management.Automation.WildcardPattern]::ContainsWildcardCharacters($targetBranches)) { # returns true if any contains 
...
        $targetBranches = $refs.value.name.Where({$branchName = $_ ; $targetBranches.Where({$branchName -like $_})})
...
        $targetBranches = $branches.name.Where({$branchName = $_ ; $targetBranches.Where({$branchName -like $_})})
}
```

**Comment by inikulshin** [comment]
@shayki5 I'm closing this.
https://github.com/shayki5/azure-devops-create-pr-task/pull/159

**Comment by inikulshin** [comment]
@shayki5 it looks like `[Management.Automation.WildcardPattern]::ContainsWildcardCharacters` can't be used for wildcard detection.

E. g. branch `GA [Stabilization]`: if it is used as is, it'll be treated as wildcard and this is wrong. If it is used escaped (**GA \`[Stabilization\`]**), `ContainsWildcardCharacters` will return `False` (see [remarks](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.wildcardpattern.containswildcardcharacters?view=powershellsdk-7.3.0#remarks)), and this is also wrong, as unescaping is required.

The best I found is:
`$targetBranch -eq [Management.Automation.WildcardPattern]::Escape($targetBranch)`

**Comment by shayki5** [comment]
Just remove spaces from your branch names 😅 
So maybe add `-and` with the `$targetBranch -ne [Management.Automation.WildcardPattern]::Escape($targetBranch)`?

**Comment by inikulshin** [comment]
The problem is not in spaces (space is not wildcard character), but in **square brackets** `[]` (and also `*` and `?`)

Branch name may contain those characters, in such case it must be escaped with `[Management.Automation.WildcardPattern]::Escape()` **before** being passed to the task.

So, currently `$targetBranch` parameter may contain both **escaped** and **unescaped** wildcard characters.

1. If it contains **unescaped** wildcard characters, it must be treated as wildcard pattern.
2. If it contains **only escaped** wildcard characters, it may be either treated as wildcard pattern or `[Management.Automation.WildcardPattern]::Unescape()`ed and then treated as string.

So, it's either

```
#case 2 in else
if ([Management.Automation.WildcardPattern]::ContainsWildcardCharacters($targetBranch)) {
	... -like ...
} else {
	$targetBranch = [Management.Automation.WildcardPattern]::Unescape($targetBranch)
	...
}
```

or

```
#case 2 in if
if ($targetBranch -ne [Management.Automation.WildcardPattern]::Escape($targetBranch)) {
	... -like ...
} else {
	...
}
```

**Comment by inikulshin** [comment]
However, the best solution is to allow explicitly distinguish those cases, e. g. `$targetBranch` and `$targetBranchWildcardPattern` (and maybe even `$targetBranchRegexPattern`).

**Comment by shayki5** [comment]
Oh ok, got it.
Go head - I trust you on creating PR :)
