### ISSUE TITLE
Create PR by other user than "project collection build service"

### ISSUE THREAD

**Issue by JaydeepUniverse** [shayki5/azure-devops-create-pr-task#160]
Hi,

I am getting `You need the Git 'PullRequestContribute' permission to perform this action` error while creating PR.

While going through the document and other github issues, it looks like that, this user "project collection build service" should be added in the security of the repo. with "Contribute to pull request" permission, which is working fine as well.

My question is, can we create the PR with any other user "abc" with the same permission "contribute to pull request"? We don't have added "project collection build service" user in the user section of the security of the repository.

This is our user permission:

![image](https://user-images.githubusercontent.com/25937808/223844451-e67b7d4b-9d05-4b9d-87e7-a9c114685d27.png)

Thanks,
Jaydeep

**Comment by shayki5** [comment]
Hi, so do you want to create the PR with a custom user?

**Comment by JaydeepUniverse** [comment]
Yes

**Comment by shayki5** [comment]
Like this issue #155 ?

**Comment by JaydeepUniverse** [comment]
Yes like this, I saw this, but I misunderstood initially but looks the same request.
do you have any update on this already?

**Comment by shayki5** [comment]
Hi @JaydeepUniverse, from what I checked it's impossible :(
https://github.com/Azure/azure-rest-api-specs/issues/10797
https://developercommunity.visualstudio.com/t/changed-createdby-with-git-create-pull-request-api/459964

**Comment by shayki5** [comment]
@JaydeepUniverse I just tested it and it's impossible, I provided my id in the body but the PR still created with the default user:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/26063853/232868809-55afe3df-daa5-469f-be9b-a47e30d9096f.png">
