### ISSUE TITLE
Enhancement - Add work item via ID/URL

### ISSUE THREAD

**Issue by smugleafdev** [shayki5/azure-devops-create-pr-task#165]
I would like the option to attach any random work item I want. That could look like:

attachWorkItems: 467001

or

attachWorkItems: 467001,467002,467003

The Link Work Items option as it is does not satisfy the simple goal of having a new work item added to the created pull request.

**Comment by shayki5** [comment]
Hi @smugleafdev, it's a good idea, it's already suggested here: #84.
I see there is a demand so I hope to add it soon :)
