### ISSUE TITLE
Multi-Branch failed on subfolder

### ISSUE THREAD

**Issue by interpeix** [shayki5/azure-devops-create-pr-task#17]
Hi, we're using your extension to auto-generate pull-requests from master to develop/* branches. Everything is working fine until we create a subfolder on develop like this "develop/MC/{branch-name}". After that the plugin fails with eror 404 trying to create pull requests on /develop/MC.

Here are some logs:
The Source Branch is: refs/heads/master
The Target Branch is: refs/heads/develop/MC
The Title is: Bajada de codigo desde Master
The Description is: Pull request automatico
Is Draft Pull Request: False
##[error]The remote server returned an error: (404) Not Found.
Finishing: Create Pull Request

That's because the branch is /develop/MC/S-20 but with the regex develop/* fails. Is there any workaround to avoid that error?

Regards

**Comment by shayki5** [comment]
Hi @interpeix,
Thank you for report the bug!
I also faced an issue if there are two folders in the branch, I will check it and I will update you :)

**Comment by shayki5** [comment]
Hi again,
I fixed the bug, please check now :)
(version 1.2.51)

Thanks,
Shayki

**Comment by interpeix** [comment]
Hi @shayki5 ,

It works perfectly well, thank you so much for your support :)

**Comment by shayki5** [comment]
You're welcome!
