### ISSUE TITLE
Is "deleteSourch" a typo?

### ISSUE THREAD

**Issue by ligz08** [shayki5/azure-devops-create-pr-task#173]
[README](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md) says `deleteSource` but [code](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/task/createPullRequest.ps1) and ADO web UI auto suggest (screenshot below) say `deleteSourch`. Typo?
<img width="241" alt="image" src="https://github.com/shayki5/azure-devops-create-pr-task/assets/7464471/6fe7e79a-97c1-4065-a49e-dae9eb87e699">

**Comment by shayki5** [comment]
Hi, it was a typo in the past and then fixed:

```
      "name": "deleteSource",
      "aliases": [
          "deleteSourch"
      ],
```
Maybe the intellisense takes the old name... anyway - `deleteSource` will work :)
