### ISSUE TITLE
Version 1.2.363 breaks pipeline for branch with forward slash

### ISSUE THREAD

**Issue by TenaciousG** [shayki5/azure-devops-create-pr-task#176]
My pipelines just pulled version 1.2.363 today and now the build breaks because it cannot find my branch.
From the error, it might look like it's struggling after escaping a forward slash in the branch-name.
`##[error]Branch 'ops%2Fcrowdin-develop-20230828.2' does not exist in repository.`

The branch is   ops/crowdin-develop-20230828.2

**Comment by TenaciousG** [comment]
@shayki5 My production pipeline is down, is this something you'll have time to look at today?

**Comment by shayki5** [comment]
Hi, it's fixed by @ligz08 :)
Can you check now?

**Comment by TenaciousG** [comment]
Seems to be working again!
