### ISSUE TITLE
Can't set Auto Complete to PR

### ISSUE THREAD

**Issue by archimedecreativa** [shayki5/azure-devops-create-pr-task#179]
In Azure sometimes i revice the error "Can't set Auto Complete to PR"
`##[warning]Can't set Auto Complete to PR 1263.
##[warning]{"$id":"1","innerException":null,"message":"Invalid argument value.\r\nParameter name: The pull request to update was not valid.","typeName":"Microsoft.TeamFoundation.SourceControl.WebServer.InvalidArgumentValueException, Microsoft.TeamFoundation.SourceControl.WebServer","typeKey":"InvalidArgumentValueException","errorCode":0,"eventId":0}
##[warning]The remote server returned an error: (400) Bad Request.
`
and the uncompleted pull request block all new pull request, when i manually complete the pull request, when the script run next time, the pull request complets

Damiano

**Comment by shayki5** [comment]
Hi, can you run it with diagnostic logs and share here the logs?

**Comment by shayki5** [comment]
@archimedecreativa ping :)
