### ISSUE TITLE
Error (404) Not Found when adding reviewers on my PR (Azure DevOps)

### ISSUE THREAD

**Issue by pbdeguzman** [shayki5/azure-devops-create-pr-task#180]
Hi,

I'm using Azure DevOps. I created a pipeline that can Create Pull Request for merging branches. Everything works well until I added a reviewer. I received **##[error]The remote server returned an error: (404) Not Found.**

![image](https://github.com/shayki5/azure-devops-create-pr-task/assets/42160425/484d5f37-e570-4b2e-9a88-33eebe3f9244)

Here's my YML file task script.
![image](https://github.com/shayki5/azure-devops-create-pr-task/assets/42160425/ea59640b-8309-482a-afd0-a16e48de2cbf)

I really need to add a reviewer to my PR. I hope you can help me with my issue. I will post the diagnostic log below.

P.S.:
I intended to change some details due to confidentiality, but I used a legitimate e-mail that can actually approve a PR.

**Comment by pbdeguzman** [comment]
Here's my diagnostic log:

![image](https://github.com/shayki5/azure-devops-create-pr-task/assets/42160425/d825b29c-d065-47f7-a125-5d33ff0657a5)
![image](https://github.com/shayki5/azure-devops-create-pr-task/assets/42160425/7c83ad63-fdbb-4753-a7e0-b88056c3a1ab)
![image](https://github.com/shayki5/azure-devops-create-pr-task/assets/42160425/e5590eb1-ce5a-45b8-88ba-f358cc162571)
![image](https://github.com/shayki5/azure-devops-create-pr-task/assets/42160425/1f743612-cb2b-457a-a312-2c2f7a19d6b3)
![image](https://github.com/shayki5/azure-devops-create-pr-task/assets/42160425/652b5063-7233-41ec-9593-b58af1929028)

**Comment by shayki5** [comment]
Hi, is it occur in every reviewers you try to put?

**Comment by pbdeguzman** [comment]
Hell sir, yes. I tried different reviewers. Even a group of reviewers.

**Comment by pbdeguzman** [comment]
Hi still receiving same error.

![image](https://github.com/shayki5/azure-devops-create-pr-task/assets/42160425/b4d33d05-0b95-4294-be22-a72e050d3fe5)
![image](https://github.com/shayki5/azure-devops-create-pr-task/assets/42160425/0c46cac3-cd9d-4201-8803-9309d52b9c4f)
![image](https://github.com/shayki5/azure-devops-create-pr-task/assets/42160425/bb3ee1b7-4bf6-4956-86e4-b94c97f1f51c)
![image](https://github.com/shayki5/azure-devops-create-pr-task/assets/42160425/c8d819e0-6aae-4de8-bcbc-933817ccc6ee)
![image](https://github.com/shayki5/azure-devops-create-pr-task/assets/42160425/03d597fd-ec08-4741-81d8-f8e35b0942b6)

**Comment by shayki5** [comment]
I checked now and I found the bug in my code and I fixed it, it's deployed now to prod, can you check now?

**Comment by pbdeguzman** [comment]
Hi, I just check my pipeline right now. The problem has been solved. Thank you so much sir!

![image](https://github.com/shayki5/azure-devops-create-pr-task/assets/42160425/1721ae6b-51da-4016-9982-d8ca1ae612ff)
