### ISSUE TITLE
Use original git commit message as description (ADO)

### ISSUE THREAD

**Issue by spaasis** [shayki5/azure-devops-create-pr-task#182]
Hi, and thanks for this tool!

By default in ADO UI the first row of the commit message is added as the PR title and all the following paragraphs are taken as the PR description.

I'm automatically updating our nuget packages in a pipeline using https://github.com/dotnet-outdated/dotnet-outdated, which generates a list of the updated packages to a file. I'm reading the file contents to the git commit:

```
          output=$(<$OUTPUTFILE)
          git commit -a -m "infra: update nugets" -m "$output"
```
This creates a beautiful commit message, but the pull request description is separate from the commit message, and since the description does not support multiple lines I can't just read the files into the PR description. Also the 4000 character limit of the description field is difficult, but could be left to ADO as it currently does in the UI by truncating the description automatically.

Is it possible somehow to use the last commit message as the PR description?

**Comment by shayki5** [comment]
Hi! 
Do you want the last commits message of the source branch will be in the description?

**Comment by spaasis** [comment]
Yes, that would be ideal. I tried leaving the `description` parameter empty, but that just resulted in no description at all

**Comment by shayki5** [comment]
You can try to use the `$(System.PullRequest.SourceCommitId` pre-defined variable.
![image](https://github.com/shayki5/azure-devops-create-pr-task/assets/26063853/e88ff6de-a754-4367-bbc6-c1915d47d9d9)

**Comment by spaasis** [comment]
Hmm yeah, I could use that to create a hyperlink to the commit to the PR description, which would be a step in the correct direction. The commit message directly in the PR description would be easier though..

**Comment by shayki5** [comment]
Is not an hyperlink, it's the commit message it self, no?

**Comment by spaasis** [comment]
Actually this has been implemented by default in the `az repos` cli  https://github.com/Azure/azure-devops-cli-extension/pull/1370 (as soon as the version 1.0 will be available in the pipeline...), so it's probably easiest to use their implementation. Here's a pipeline for it:

```
      - checkout: self
        persistCredentials: true
      - bash: >
          az repos pr create 
          --auto-complete true 
          --delete-source-branch true 
          -s '$(sourceBranch)'
          --squash true
        displayName: Create a pull request
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
```

I'll close this since the problem is basically resolved.
