### ISSUE TITLE
Not working on ubuntu-latest

### ISSUE THREAD

**Issue by aleksandra-insight** [shayki5/azure-devops-create-pr-task#187]
Hello!

I was trying to implement this extension, but I am getting the following error: **##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.**
I assume that is because I run _pool: vmImage: ubuntu-latest_. Is there any workaround for that? 

This is my first time building a ADO CICD pipeline and I am a little lost on how else I can name automated pull requests. 

Thank you!

**Comment by shayki5** [comment]
Hi, currently the task working only on windows agent, so you need to run it on a job with `pool: windows-latest`.
