### ISSUE TITLE
Delete Source Branch feature is not working with the Azure DevOps Repository

### ISSUE THREAD

**Issue by prafuljain-zehntech** [shayki5/azure-devops-create-pr-task#188]
The "Delete Source Branch" feature does not work with the Azure DevOps Repository. I've attached a reference of the pipeline's task settings.

![2024-11-13 14_17_57-2ERP-CI-16 0-DEV-TO-17 0-DEV-clone - Azure DevOps Services](https://github.com/user-attachments/assets/ada46c57-4595-4d59-9a5e-5dace61a35cd)

**Comment by shayki5** [comment]
Hi, can you share the task logs?

**Comment by prafuljain-zehntech** [comment]
Hello Shayki,

Thank you for looking into it. It was the permission issue and we have resolved now. Please close the issue at your end.


Thanks & Regards,

Praful Jain

Tech Lead | Zehntech Technologies<https://www.zehntech.com/>

Team Email: ***@***.***

Mobile: +917509654727

Book time with ***@***.***/meetingtype/dwFjPeDpYU-fKg3yFhUeww2?anonymous&ep=mcard>


Empower Your Business with Our Odoo Apps<https://www.zehntech.com/erp-crm/odoo-apps/> | Odoo Themes<https://www.zehntech.com/erp-crm/odoo-theme/>


________________________________
