### ISSUE TITLE
Question Windows Machines only

### ISSUE THREAD

**Issue by GuySimcox** [shayki5/azure-devops-create-pr-task#2]
Hi I'm getting a 403 forbidden. Yet I've enabled OAuth. Might this be due to the online server not being Windows. I'm unsure as this is Azure DevOps online not local prem.

Thanks for any assistance 
Guy

**Comment by shayki5** [comment]
Hi @GuySimcox ,  
The task support only windows machines (the agent should be in Windows).
Can you attach a photo of the error?
Thanks,
Shayki

**Comment by GuySimcox** [comment]
@shayki5 Thanks for your response, apologies there wasn't much more to the error message except for 403 forbidden. Security of some sort I guess. 

However I've found another way to do what I wanted which uses the Azure DevOps CLI method.

[https://docs.microsoft.com/en-gb/cli/azure/ext/azure-devops/repos/pr?view=azure-cli-latest#ext-azure-devops-az-repos-pr-create]

Thanks
Guy

**Comment by shayki5** [comment]
Hi Guy,
Yea, it another great way to create a PR.
Thanks for your info!

Kind regards,
Shayki
