### ISSUE TITLE
Remote server returned a 404

### ISSUE THREAD

**Issue by rszemplinski** [shayki5/azure-devops-create-pr-task#21]
Don't know what I'm doing wrong. Added all the permissions to the Project Collection Service Users and everything.

![image](https://user-images.githubusercontent.com/5331990/71999068-bffa3c00-320e-11ea-9231-5e28c0c91252.png)

**Comment by rszemplinski** [comment]
Should also note that I am doing this in a Release pipeline

**Comment by shayki5** [comment]
Hi @rszemplinski,

404 is not a permissions issue, can you please run the pipeline again with the variable `system.debug` = `true` and share here the logs?

Thanks,
Shayki

**Comment by rszemplinski** [comment]
So is it because we are using the old url?

Url: `digiop.visualstudio.com`

![image](https://user-images.githubusercontent.com/5331990/72012231-939fe900-3229-11ea-98ac-b4181c435ecc.png)

**Comment by shayki5** [comment]
Thank you!
You are right, this is a special API URL and I didn't handle the old URL format.
I fixed it now and I uploaded anew version, please check if it works now :)

**Comment by rszemplinski** [comment]
So, it was weird. It threw an error the first time throwing up this huge 404 message than I ran it a second time and now it works!

Thank you sir!

**Comment by shayki5** [comment]
You're welcome!
Also locally if I run the API with the old URL I didn't get the results, but log-in page and then the results, so I guess this is the reason.
Anyway, I recommend moving to the new URL format :)

**Comment by rszemplinski** [comment]
Yeah, actually just had a conversation about that with some coworkers. Plan on doing that soon.

Anyways, thanks again for your help!
