### ISSUE TITLE
Fail in setting auto-complete

### ISSUE THREAD

**Issue by eliiotz** [shayki5/azure-devops-create-pr-task#23]
Hi, I suddenly found that the task will fail in setting auto complete now. I have turned on the debug mode and the log is as below.

According to the log, I think the exception should happen when requesting user graph api. 
[API in official document](https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/Users/List?view=azure-devops-rest-5.1) is https://vssps.dev.azure.com/xxx/_apis/graph/users?api-version=5.1-preview.1 (it works well)
What I see in log is https://xxx.visualstudio.com/_apis/graph/users?api-version=4.1-preview.1

Does it mean that Azure Dev Ops has changed their API? I have checked that using 4.1-preview.1 as api-version still works.

**Debug log**
##[debug]GET https://xxx.visualstudio.com/_apis/graph/users?api-version=4.1-preview.1 with 0-byte payload
##[debug]Leaving RunTask.
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]CreateAzureDevOpsPullRequest :  
##[debug]Azure DevOps
##[debug]Service Status Support @AzureDevOps 
##[debug]At D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.59\createPullRequest.ps1:80 char:9
##[debug]+         CreateAzureDevOpsPullRequest -sourceBranch $sourceBranch -tar ...
##[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
##[debug]    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,CreateAzureDevOpsPullRequest
##[debug] 
##[debug]Script stack trace:
##[debug]at CreateAzureDevOpsPullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.59\createPullRequest.ps1: line 276
##[debug]at CreatePullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.59\createPullRequest.ps1: line 80
##[debug]at RunTask, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.59\createPullRequest.ps1: line 38
##[debug]at <ScriptBlock>, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.59\createPullRequest.ps1: line 438
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]Microsoft.PowerShell.Commands.WriteErrorException:  
##[debug]Azure DevOps
##[debug]Service Status Support @AzureDevOps

**Comment by shayki5** [comment]
Hi @eliiotz,
Did it work for you in the past?
It fails because you use the old URL format - `https://xxx.visualstudio.com` and not the new format `https://dev.azure.com/xxx`.
Can you change the URL to the new format?

**Comment by Gabhala** [comment]
I'm seeing a similar problem on Azure DevOps Server 2019 (on-premise).  It seems that the DevOps Server API does not include the Graph API - https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-server-rest-5.0

**Comment by shayki5** [comment]
@Gabhala You are right, it looks like the graph API not supports Azure DevOps Server. I will add it to the Release Notes as a known issue.

**Comment by eliiotz** [comment]
@shayki5 This is a system variable and I got below error when trying to rewrite it:

Cannot override system variable 'System.TeamFoundationCollectionUri'

**Comment by shayki5** [comment]
@eliiotz  It's in the organization settings:

![image](https://user-images.githubusercontent.com/26063853/72262169-0bea1e00-361f-11ea-8c17-df7a9d3e52ec.png)

**Comment by eliiotz** [comment]
Thanks! I found the setting. I have requested the change to org admins, but not quite sure if it may impact other projects under the org.

I think it should be okay to close this issue. And it would be great if we can make the task compatible with old url. Can I contribute to the code base?

**Comment by shayki5** [comment]
I make the task compatible with the old URL in other API calls, but in this specific API, I can't get results.
Check the code to see how I handled it, if you will make it work you can of course open a PR and contribute :)

**Comment by shayki5** [comment]
This issue fixed by @eliiotz in PR #24 :)
