### ISSUE TITLE
Pull request created even if there are no changes to merge between the selected branches

### ISSUE THREAD

**Issue by SebastienChrist** [shayki5/azure-devops-create-pr-task#37]
Hello,

On dev.azure.com, you cannot create a new pull request if there are no changes to merge between the selected branches.

With the create-pr-task, a pull request is created. Then, you should close or abandon the pull request.
A message in the log should be enough in this case.

Regards,

![PR_WithNoChanges](https://user-images.githubusercontent.com/54934004/79238494-bae10480-7e6f-11ea-83b7-6932b42c734b.JPG)

**Comment by shayki5** [comment]
Hi @SebastienChrist,
You are right! I will fix it soon :)
Thank you!

**Comment by shayki5** [comment]
Hi @SebastienChrist,
I fixed it :)
Please try now and update if you get a warning instead of a PR.

**Comment by SebastienChrist** [comment]
Hi @shayki5,

Thank you, it works ! 👍 
The task has Success Status and a warning appears in the log 

`##[warning]{"$id":"1","innerException":null,"message":"TF401179: An active pull request for the source and target branch already exists.`
