### ISSUE TITLE
Getting : [error]Cannot convert 'System.String[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported.

### ISSUE THREAD

**Issue by TarunSingh12April** [shayki5/azure-devops-create-pr-task#4]
Hi Shayki,

I am getting below error. I am using azure pipelines windows vs2017-win2016 agent. 

![image](https://user-images.githubusercontent.com/50168434/65680981-aaa13d80-e075-11e9-9847-fe6546e0a48d.png)

I have allowed Project Collection Build Service user to contribute to pull requests.
Please help.

Regards
Tarun

**Comment by shayki5** [comment]
Hi @TarunSingh12April, 
Can you share please the task configuration?
Thank you,
Shayki

**Comment by shayki5** [comment]
Hi again @TarunSingh12April,
I updated the extension (to version 1.0.44) and I think it also fixed this error, can you update and check please?
Thank you,
Shayki

**Comment by TarunSingh12April** [comment]
Thanks Shayki.

I am still getting the same error.
Task looks like:
![image](https://user-images.githubusercontent.com/50168434/66105292-ba220880-e5d8-11e9-8037-86d3a5e6281c.png)

I've one query, in extension tab of Azure organizational settings I can see that your extension is installed in my project with latest version 1.0.44. But in task log, 1.0.0. is mentioned as version. Is it normal?
![image](https://user-images.githubusercontent.com/50168434/66105562-68c64900-e5d9-11e9-8dd3-f0009d85eb08.png)

Thank you.
Tarun

**Comment by TarunSingh12April** [comment]
Hi @shayki5 , Thank you so much for your continuous help.

It seems issue still persists. Version 1.0.45 is reflecting in organization settings and I have used valid email address for reviewers field, still getting same error:
"Cannot convert 'System.String[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported."

![image](https://user-images.githubusercontent.com/50168434/66112463-89e26600-e5e8-11e9-8cae-859fc4232bb1.png)

![image](https://user-images.githubusercontent.com/50168434/66112547-b8604100-e5e8-11e9-9913-684b98297fde.png)

Please help.. :(

Regards,
Tarun

**Comment by TarunSingh12April** [comment]
Hi @shayki5 ,

I re-installed the extension and created new pipeline. It is showing different error now: 
"ConvertFrom-Json : Invalid JSON primitive: Page."

![image](https://user-images.githubusercontent.com/50168434/66114963-83a2b880-e5ed-11e9-9aa2-28d44191948d.png)

![image](https://user-images.githubusercontent.com/50168434/66115052-b2b92a00-e5ed-11e9-8c12-987c9e17286d.png)

Thank you,
Tarun

**Comment by TarunSingh12April** [comment]
@shayki5 I forgot to enable Oauth in new pipeline, I have enabled it. It is now showing reviewers id. But still getting same error: "ConvertFrom-Json : Invalid JSON primitive: Page."

**Comment by shayki5** [comment]
@TarunSingh12April Ok, it's look like you still get an error when the task try to create PR but it can't print the error correctly and you get the Json error. 

I fixed it and updated the extension now, please remove the task and add him again to the build definition (it should be enough, but I'm not sure) and try again.

By the way, did you gave permissions to the build service account?

Thanks,
Shayki

**Comment by TarunSingh12April** [comment]
Hi @shayki5,

Still no luck, same error is coming with version 1.0.46. I tried creating new pipeline, still same error.

However the last link which it is accessing (prior getting failed) gives "404 Page not found" error.
link: https://dev.azure.com/<my_project_name>/<git_repo_name>/_apis/git/repositories/<my_project_name>/<my_git_repository_name>/pullrequests?api-version=5.0

Is there is anything I can do to rectify this from my side.

Our code is not in Azure repos, we are using Github for that.

Thank you,
Tarun

**Comment by shayki5** [comment]
Hi @TarunSingh12April,
That explain the error... the extension can create a PR for Azure DevOps (Repos), **not** for GitHub :(
It can be useful feature to add, but it will be a lot of work, I will start check it.

Best regards,
Shayki

**Comment by TarunSingh12April** [comment]
@shayki5 ohhh... :(   However thank you so much for your continuous efforts. I am pretty sure you will add this feature as well.

Regards,
Tarun

**Comment by shayki5** [comment]
You're welcome! 
I will keep you update here.

**Comment by shayki5** [comment]
Hi @TarunSingh12April,
I have a good news! I updated the extension with GitHub support :)
The new version is 1.2.1 (it should be updated automatically, check if the Git Type radio buttons exist in the task, if not - uninstall and re-install....).
If you have any questions about it you can ask here.

Kind regards,
Shayki

**Comment by shayki5** [comment]
Hi Tarun,

Great! I glad to hear it :)
If you will find a bugs or do you think about an improvements please let e know :)

Thank you,
Shayki

**Comment by TarunSingh12April** [comment]
Sure Shayki.

Regards,
Tarun
