### ISSUE TITLE
Make approvers required not optional

### ISSUE THREAD

**Issue by TheFairey** [shayki5/azure-devops-create-pr-task#40]
Hi,

Got this working and it's perfect so thanks, one request, is there a way to make the approvers required rather than optional when you create the pull request?

Cheers

Si

**Comment by shayki5** [comment]
Hi @TheFairey,

I glad you enjoy the task :)
The problem is, if I will do it required it will affect everybody who use the task and I don't know if they want it...
I will keep this issue open for a while, if more people will comment that they want it I will consider to make it required.
Is it make sense?

Kind regards,
Shayki

**Comment by TheFairey** [comment]
I understand, could we maybe have 2 entry fields instead of one and have one for required approvers and one for optional?

**Comment by TheFairey** [comment]
that way it would be backwards compatible as the new field would be for required approvers only?

**Comment by shayki5** [comment]
But same issue - pipelines with this task or new pipelines will be required to put approvals in the new field.

**Comment by TheFairey** [comment]
Can you make the required approvers an optional field? Sounds odd I know to make a required thing optional but I think it would make sense?

**Comment by shayki5** [comment]
What do you mean 'required approvers'? that in the PR they will be require to approve?

**Comment by TheFairey** [comment]
Correct so they appear in required rather than optional here
![image](https://user-images.githubusercontent.com/900332/81832633-bf4f1a80-950c-11ea-8b83-0ef4fab766e7.png)

**Comment by shayki5** [comment]
@TheFairey Oh! it looks like something new:
https://devblogs.microsoft.com/devops/introducing-the-new-pull-request-experience-for-azure-repos/
I will add another field for the required :)

**Comment by shayki5** [comment]
Hi @TheFairey,
I uploaded a new version :)
Now, if you want to add a required reviewer you need to add `req:` before.
For example:
`req:test@gmail.com`
Please test it and update me if it works well for you.

Best regards,
Shayki

**Comment by TheFairey** [comment]
Awesome thanks will take a look later today

**Comment by TheFairey** [comment]
tried it earlier and it failed but not some more updates so will try again now

**Comment by shayki5** [comment]
ok, thanks. if it failed please post here the error.

**Comment by TheFairey** [comment]
Worked great thanks
