### ISSUE TITLE
PR with special character # not working

### ISSUE THREAD

**Issue by jsmesquita** [shayki5/azure-devops-create-pr-task#42]
When I creating PR with a source branch name that contains this character # I'm getting:  The remote server returned an error: (404) Not Found.

![2020_05_19_09_26_02_API ChatbotUnidas Blip CD_API ChatbotUnidas Blip CD_81_Pipelines](https://user-images.githubusercontent.com/24892301/82326411-28bea580-99b3-11ea-826e-be29febd2df9.jpg)

**Comment by shayki5** [comment]
Hi @jsmesquita 
Thank you for reporting it!
I will check it and will update you.

**Comment by shayki5** [comment]
@jsmesquita I fixed the bug :)
Please try now if it works for you.

**Comment by jsmesquita** [comment]
It works! Thank you so much!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shayki5** [comment]
Great! You're welcome :)
