### ISSUE TITLE
AzureDevOps: Incorrect "commitMessage" option in "SetAutoComplete"

### ISSUE THREAD

**Issue by ReshimVse** [shayki5/azure-devops-create-pr-task#44]
Hi, @shayki5!

I noticed that "commitMessage" does not apply to "SetAutoComplete" in AzureDevOps.
I researched this case and found an error with option:
![image](https://user-images.githubusercontent.com/44438320/83434486-47a54900-a443-11ea-940c-b9733900cb6f.png)

**Microsoft Docs**: 

- https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20requests/update?view=azure-devops-rest-5.1

Can you check this case and update this option?

**Comment by shayki5** [comment]
Hi @ReshimVse,
Thank you! look like you're right!
Could you open a Pull Request with your fix?

**Comment by ReshimVse** [comment]
@shayki5 Done!
https://github.com/shayki5/azure-devops-create-pr-task/pull/45/files

**Comment by shayki5** [comment]
Great!
It will be in production in 15 minutes :)
