### ISSUE TITLE
Unable to connect to Remote Error

### ISSUE THREAD

**Issue by SrivathsanJ** [shayki5/azure-devops-create-pr-task#49]
Hello,

I am trying to use this task for azure devops git repo. It is throwing 
1. Unable to connect to Remote error on self hosted agent (Windows)
2. The remote server returned 404 error on Hosted agent (Windows)
I have added the option to use OAuth in Agent job
Allowed contribute to Pull request permission to build users.
Can you help out in understanding why i am getting this error.

**Comment by shayki5** [comment]
Hi @SrivathsanJ, could you share here the task configuration and also run it with `system.debug` = `true` and share the logs?

**Comment by SrivathsanJ** [comment]
i have used the basic configurations. Build.SourceBranch as source and master as target.
For some reason $(Build.SourceBranch) is not getting the value. it is not showing the branch value in the logs. could this be the issue ?

**Comment by shayki5** [comment]
I can't know without seeing the configurations and the logs...

**Comment by SrivathsanJ** [comment]
PFA the logs you had asked. I have masked Org id and Project ID. Rest all are the same.
Build.SourceBranch and Build.SourceRepo variables are not getting replaced with values. So i added the actual branch name in the task
[PR_Task_Log.log](https://github.com/shayki5/azure-devops-create-pr-task/files/4785841/PR_Task_Log.log)

**Comment by shayki5** [comment]
Thank you!
If you enter this url `https://My_ORG.visualstudio.com/Project_ID/_apis/git/repositories/Repo_ID/diffs/commits?baseVersion=Release_2&targetVersion=master&api-version=4.1&$top=2` in the browser, do you get results? (replace with your real org/project/repo/ ID)

**Comment by SrivathsanJ** [comment]
yes. i get the commit differences

**Comment by shayki5** [comment]
Please see issue #21, it because you use the old URL, can you run it again? (it should work after you logged-in in the browser)

**Comment by SrivathsanJ** [comment]
The Old url api call is working when i try locally in my browser. and i have another org with my personal account which is using the same pattern and works fine in the release pipeline. 
strange. let me try this now and update. 
Thanks

**Comment by SrivathsanJ** [comment]
It's creating the pull request now.. However, my self hosted agent is is still using the old url(even on a new release). Hosted agents are able to pickup new url and create PR. But the build.sourcebranch and build.sourcerepo variables are not retuening the values. I had to manually select the repo and branch name. Is there way to get it working.. 
Thanks

**Comment by shayki5** [comment]
So it works now when you specify the values?
BTW - there is no pre-defined `build.sourcerepo` variable.

**Comment by SrivathsanJ** [comment]
yes. if i manually specify the branch name and select Repo name for "Repository to use" instead of "current repository build".
I was actually referring to "$(Build.Repository.Name)" that's also no retrieving the value

**Comment by shayki5** [comment]
And also $(Build.SourceBranch) not working?

**Comment by SrivathsanJ** [comment]
Yes. that is not also not working. I had to manually enter the branch

**Comment by shayki5** [comment]
@SrivathsanJ could you share exactly your configuration? it's in a release pipeline?

**Comment by PaulIvan** [comment]
I've got a similar issue when trying to create PR's from github to Devops. allowed token and all settings but failing at the same line. any clue? 
[checkout-from-github.txt](https://github.com/shayki5/azure-devops-create-pr-task/files/4836790/checkout-from-github.txt)
[createpr-devops.txt](https://github.com/shayki5/azure-devops-create-pr-task/files/4836791/createpr-devops.txt)

**Comment by shayki5** [comment]
Hi @PaulIvan, I see in your logs `INPUT_REPOTYPE: 'Azure DevOps'`, but it should be GitHub, can you check?

**Comment by PaulIvan** [comment]
> Hi @PaulIvan, I see in your logs `INPUT_REPOTYPE: 'Azure DevOps'`, but it should be GitHub, can you check?

if I select Github, it will try to push the PR on github I don't need that. I want the PR to be published in Devops from Github

**Comment by shayki5** [comment]
@PaulIvan what do you mean "PR to be published in Devops from Github"? where is the repo?

**Comment by PaulIvan** [comment]
The scenario is the following:

- I have this test repo on my github. https://github.com/PaulIvan/ALAppExtensions/
- Whenever a PR is made against this github repo a pipeline is triggered in Devops using the azure github connector
- I want the pipeline task to push the content of the github PR in a duplicate repo in devops (which I already made) as another PR

Is that not something this extension can do?

![image](https://user-images.githubusercontent.com/617029/85988797-db8d1500-b9ef-11ea-839a-3497b524497f.png)

**Comment by shayki5** [comment]
@PaulIvan I'm sorry but not :/ 
You should clone the repo from GitHub to Azure DevOps and update it there in an automated way (each commit to GitHub will update the repo in Azure DevOps - you can create a build for that), when all the repo will be in Azure DevOps you can use the extension to create the PR in Azure DevOps (not from GitHub, from branch and to branch both in ADO).

**Comment by shayki5** [comment]
Closing because there is no more info from the issue opener.
