### ISSUE TITLE
Multi target branch

### ISSUE THREAD

**Issue by taniluc** [shayki5/azure-devops-create-pr-task#5]
Hi!
How I can manage the Target branch name when I want to send a multi pull request and I have my branches into a folder, like this.

![image](https://user-images.githubusercontent.com/54959604/65911873-8782d080-e38a-11e9-9738-682076349705.png)

**Comment by shayki5** [comment]
Hi @taniluc,
You can do this:
`DEV/DEV_*`
Please check and upate me if it will success :)
Thank you,
Shayki

**Comment by taniluc** [comment]
Hello @shayki5, 
I tried with both, but didn't work for the branches in the folder.
I receive this error: 

##[debug]Invoke-RestMethod : {"$id":"1","innerException":null,"message":"TF401398: The pull request cannot be activated because the source and/or the target branch no longer exists, or the requested refs are not branches","typeName":"Microsoft.TeamFoundation.Git.Server.GitPullRequestCannotBeActivated, Microsoft.TeamFoundation.Git.Server","typeKey":"GitPullRequestCannotBeActivated","errorCode":0,"eventId":3000}
## [error] Error on the remote server: (400) Incorrect request.
Thanks

**Comment by shayki5** [comment]
@taniluc Can you please run the task with `system.debug` = `true` and share here all the log? (not only the error).
Thank you!

**Comment by taniluc** [comment]
@shayki5, 
I have others branches out side of the folder DEV, and the pull request was created for this ones but not for the branches on the folder.

![image](https://user-images.githubusercontent.com/54959604/66063793-5a0c6300-e501-11e9-8a37-2229847cdc07.png)

**Comment by shayki5** [comment]
Hi @taniluc,
I fixed the bug, please update the extension to version 1.0.44 and check (with `DEV/*`) :)
Thank you,
Shayki

**Comment by taniluc** [comment]
Hi @shayki5,
Well, with your fix now it perfectly works!

![image](https://user-images.githubusercontent.com/54959604/66080643-b7191080-e523-11e9-89b9-eaf8c4cf9532.png)

Thank you very much!

**Comment by shayki5** [comment]
Great :)
Thanks for sharing!
