### ISSUE TITLE
REST call to commitsBatch is failing with: "Microsoft Internet Explorer's Enhanced Security Configuration is currently enabled on your environment...."

### ISSUE THREAD

**Issue by puremcc** [shayki5/azure-devops-create-pr-task#51]
When I run this with system.debug=True, I get the following error message on the step:

##[debug]POST https://dev.azure.com/MYORG/90b82c25-01be-489a-8d49/_apis/git/repositories/a4a02d21-ba3c-4fc5-b90b/commitsBatch?api-version=4.1 with -1-byte payload

> Microsoft Internet Explorer&#39;s Enhanced Security Configuration is currently enabled on your environment. This enhanced level of security prevents our web integration experiences from displaying or performing correctly.

I'm not sure if I will be able to change this configuration on my company's build agents. Is there possibly something else I can do, or that I'm missing?

**Comment by shayki5** [comment]
hI @puremcc,
If you now link the work items is it works? or you get the same error in another API call?

**Comment by puremcc** [comment]
The log above was from a run where I had the `Link work items` option checked (True).
I have now tried running with the `Link work items` option unchecked (False), and I no longer see any error, but the PR still does not get created.

**Comment by shayki5** [comment]
Thanks for the info.
Can you run the pipeline with `system.debug` = `true` and share here the logs?

**Comment by shayki5** [comment]
After Mike shared the logs with me we noticed it's was a permissions issue.

**Comment by puremcc** [comment]
Thanks @shayki5 for you help and prompt email responses! Great extension. Very valuable for me and my client.

Note to others who may run into a similar issue: you may also need to grant  the build service account Contributor permission on the target **project** in addition to the target **repo**.
