### ISSUE TITLE
Pull Request dosent gets created after successfully execution of the task in azure devops

### ISSUE THREAD

**Issue by upendertiwari** [shayki5/azure-devops-create-pr-task#52]
Hi ,

We are using  this "CreatePull Request" task to create a pull request to master after completion of deployment to a stage , the task gets executed successfully however there is no pull request getting created.

Success screen shot
![image](https://user-images.githubusercontent.com/53815920/86483949-c3602180-bd72-11ea-8fc1-075d7ef5bfe7.png)

[LogsForCreatePull.txt](https://github.com/shayki5/azure-devops-create-pr-task/files/4870476/LogsForCreatePull.txt)

Upender

**Comment by shayki5** [comment]
Hi @upendertiwari!
Did you give the permissions with the Access Token?
Can you run the pipeline with `system.debug` = `true` and share again the logs?

**Comment by upendertiwari** [comment]
Yes, however i see below error when i enabled the system.debug=true, 
ERROR : Microsoft Internet Explorer&#39;s Enhanced Security Configuration is currently enabled on your environment. This enhanced level of security prevents our web integration experiences from displaying or performing correctly. To continue with your operation please disable this configuration or contact your administrator.

can you give more details to disable  Enhanced Security Configuration. so that i will coordinate with administrator to resolve it.

please find the attached logs with system.debug=true. 
[AzureCreatePullRequestDebugTrue.txt](https://github.com/shayki5/azure-devops-create-pr-task/files/4877906/AzureCreatePullRequestDebugTrue.txt)

**Comment by shayki5** [comment]
@upendertiwari thanks.
I still see in the response like you don't have permissions.
Do you use YAML build or the classic editor build?

**Comment by upendertiwari** [comment]
Hi,

I am using classic editor build. Can you provide me which permission i don't have and where to locate them. So that i can contact the admin to get the permissions.

**Comment by shayki5** [comment]
Maybe it's indeed related to the error you mentioned:
`ERROR : Microsoft Internet Explorer's Enhanced Security Configuration is currently enabled on your environment. This enhanced level of security prevents our web integration experiences from displaying or performing correctly. To continue with your operation please disable this configuration or contact your administrator.`
Can you try to run it without the checkbox of "link work items"?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@shayki5 I ran into the exact same issue and running without the checkbox of "link work items" did not help.
There are no errors in the logs (even with debug enabled) and the build pipeline also succeeded. Any guidance on how to troubleshoot this further?

**Comment by shayki5** [comment]
Hi @BhargaviAnnadevara-MSFT, could you share the logs here?
Did you grant the permissions?

**Comment by BhargaviAnnadevara-MSFT** [comment]
Hello @shayki5, Thanks for the quick response! Apologies, looks like the permissions were missed while cloning the pipeline. I am able to see the Pull request being created now. And also able to add reviewers and link work items. Will test auto-complete and get back.

One quick question now would be:
Can I target the PR to multiple branches separated by a semicolon or comma?
_For example:_ Create a PR to both `dev` and `master` branches. I see that the document mentions multi-branch targeting with wildcards like `*`.
Please clarify.

**Comment by shayki5** [comment]
Hi @BhargaviAnnadevara-MSFT,
I'm happy you success to create the PR :)
The multi-target branch works in this way:
`release/*` - will create for `release/1` and `release/1`
2 totally name different branches should be interesting also, I can check if I can add this feature.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@shayki5 Correct. Sure, it would be really helpful if this can be supported. Thank you!

**Comment by shayki5** [comment]
Hi @BhargaviAnnadevara-MSFT,
I added this feature 😀
Now you can specify multi-target branch with `;` - for example: `dev;master`.

**Comment by shayki5** [comment]
@BhargaviAnnadevara-MSFT did you check the last version?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@shayki5 This is great! Thank you very much for the quick implementation.
I haven't had a chance to test it out yet, but will do soon and let you know. Thanks again!

**Comment by shayki5** [comment]
@upendertiwari any update? is it sill failed for you?

**Comment by upendertiwari** [comment]
hi Shayki,
Still now working , so dropped this feature and doing pull request to master manually,

Regards,
Upender Tiwari

**Comment by shayki5** [comment]
@upendertiwari I'm sorry about it :(
It's probably some security policies in your company.
