### ISSUE TITLE
Unable to create pull request

### ISSUE THREAD

**Issue by Bakkiya8** [shayki5/azure-devops-create-pr-task#53]
Hey shayki5!!

I have tried to create the pull request using classic editor using "Create Pull Request".

Steps i have followed`
I have provided create pull request---allow in project settings repositories
Enabled Allow scripts to access the OAuth token
added task in class editor.

 Task ran successfully but the pull request is not created.

guide me where i need to provide the PAT.

Getting this error:

The version descriptor  could not be resolved to a version in the repository

**Comment by shayki5** [comment]
Hi @Bakkiya8!
Could you run it again with `system.debug` = `true` and share here the full log?

**Comment by shayki5** [comment]
@Bakkiya8 do you still facing an issue?

**Comment by shayki5** [comment]
Closing because of no response.
