### ISSUE TITLE
Multistring Description

### ISSUE THREAD

**Issue by AlexVasiukov** [shayki5/azure-devops-create-pr-task#54]
Dear Shayki5,
Are there any options to create PR with multi-line description? As I know, multistring output vars are not allowed in ADO. We also cannot use powershell string functions in CreatePullRequest@1. Am I missed something? 
Thanks in advance!

**Comment by shayki5** [comment]
Hi @AlexVasiukov,
You can put a multiline description with `<br/>`.
For example:
![image](https://user-images.githubusercontent.com/26063853/87155353-7d034900-c2c3-11ea-988b-9a582c8d4764.png)
Result:
![image](https://user-images.githubusercontent.com/26063853/87155368-82f92a00-c2c3-11ea-9619-a083fe4bfb46.png)

**Comment by shayki5** [comment]
@AlexVasiukov did you try it?

**Comment by AlexVasiukov** [comment]
Hello @shayki5,
Yes. I tried and it's work both in cloud and on-prem Azure DevOps.
Thanks a lot! Much appreciate!

**Comment by shayki5** [comment]
@AlexVasiukov Great 😀
Thank you for the update!

**Comment by AlexVasiukov** [comment]
Sorry, @shayki5, I found a version in which <br/> doesn't work. It's On-premises.
**Version Dev17.M153.5**

**Comment by shayki5** [comment]
@AlexVasiukov the multi-line doesn't work? it's Azure DevOps Server 2019?
