### ISSUE TITLE
Skip creating a pull request if one already exists

### ISSUE THREAD

**Issue by momerm** [shayki5/azure-devops-create-pr-task#6]
If I already have an existing pull request from the source branch to the target branch, the task returns the following error causing the build to fail.

##[error]The remote server returned an error: (409) Conflict.

Is it possible to skip creating a pull request if there is one already open?

**Comment by shayki5** [comment]
Hi @momerm,
I updated the extension and implemented it :)
Now if there is a PR the task will not be failed with error but will display a warning:
![image](https://user-images.githubusercontent.com/26063853/66026648-f6366a00-e501-11e9-9100-eeba2195a03d.png)
Please update the extension to version 1.0.41 and check :)
Thank you,
Shayki

**Comment by momerm** [comment]
Wow that was quick. It's working great now. Thank you!

**Comment by shayki5** [comment]
You're welcome!

**Comment by slandsaw** [comment]
What if you still want a pull request to be created?

**Comment by slandsaw** [comment]
In other words, would it be possible to create a new PR even if there is already an open one?

**Comment by shayki5** [comment]
Hi @slandsaw, it impossible due to Azure DevOps limitation:
![image](https://user-images.githubusercontent.com/26063853/80642154-a2c3d480-8a6e-11ea-8f63-cf5d7c0afc3e.png)

**Comment by slandsaw** [comment]
Thank you for the speedy reply!
