### ISSUE TITLE
Error on try run release pipeline in Azure DevOps

### ISSUE THREAD

**Issue by victorhcosta** [shayki5/azure-devops-create-pr-task#61]
Hi,

I am using this "CreatePull Request" task to create a pull request to master after completion of deployment to a stage, but I stay receiving the error "TF401027: You need the Git 'PullRequestContribute' permission to perform this action" even after configuring permissions following the instructions in the README.

**Comment by shayki5** [comment]
Hi @victorhcosta ,

Could you check this https://github.com/shayki5/azure-devops-create-pr-task/issues/28#issuecomment-584661744 and this https://github.com/shayki5/azure-devops-create-pr-task/issues/31#issuecomment-598256240? and issue #35.
I think it can helps you :)

Kind regards,
Shayki

**Comment by victorhcosta** [comment]
Thanks, I managed to adjust and it's working properly.
