### ISSUE TITLE
warning should be error and automatically complete the created pr when the policy sayings at least 1 reviewer?

### ISSUE THREAD

**Issue by daxu7509** [shayki5/azure-devops-create-pr-task#62]
hi,
I use vsts's git repo and installed this extension.
When a PR is created, Is it possible to auto complete it as well when I setup a policy saying at least 1 reviewer needed?

Also the task will gives an warning when things go wrong (e.g.  ##[warning]{"$id":"1","innerException":null,"message":"TF401179: An active pull request for the source and target branch already exists.","typeName":"Microsoft.TeamFoundation.Git.Server.GitPullRequestExistsException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitPullRequestExistsException","errorCode":0,"eventId":3000}

But this should be a failure other than a warning, as the next step needs to be stopped.

**Comment by shayki5** [comment]
Hi @daxu7509!
If your repo it's in Azure DevOps (and not GitHub) you can set "auto complete":

![image](https://user-images.githubusercontent.com/26063853/91760044-52ef4880-ebdb-11ea-93c6-72d4fa6783c1.png)

In YAML:
`autoComplete: true`

Regarding your second point, I made it as a warning because of issue #6.
Maybe I can make a checkbox if it will be an error or a warning.
What do you say?

**Comment by daxu7509** [comment]
hi, 
I did set auto complete to be true. 
The problem is that in my repo, there is a policy that at least one reviewer has to approve it before complete. As a result, it didn't auto complete (some human need to click the approve button).
However, we do want the PR to be 100% auto-completed in some scenarios:
Say we have 3 branches: Master, Sprint, Stories.
Scenario A:
1. Our sprint works are done in individual stories branches and then merged to sprint branch.
2.. We merge from sprint to master and deploy to prod.
Scenario B:
1. If there is a hotfix, we do it in a story branch and merge to master directly.
2. We deploy from master and then merge back to sprint.

As you can see, when we merge from sprint branch to master, every story is already reviewed so **we don't** want someone to approve it.
But when we merge for hotfix purposes, we **do** want an approval.

In azure cli's command az repos pr, there is an option to **bypass-policy**,  [https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/pr?view=azure-cli-latest](url). So looks like it is possible to ignore the policy and force pull request to complete?

Regarding to the second point, it would be great if this can be a checkbox.

**Comment by shayki5** [comment]
Oh ok, I understand.
I can add also the bypass option.
I will start work in it + the checkbox :)

**Comment by daxu7509** [comment]
Hi,
I done the code of adding bypass option, but not sure how can I share that code with you? (not sure how to add a checkbox in azure devop task)

**Comment by shayki5** [comment]
Hi, you can fork the repo, then add your changes and create a PR to my repo.
See here: https://github.com/firstcontributions/first-contributions

**Comment by daxu7509** [comment]
ok, I think I got how github works now.
I added some code to switch warning and error when auto complete can't be set or a pr already exists as well.

**Comment by shayki5** [comment]
Great! I will review in the next hours :)
Thank you!

**Comment by daxu7509** [comment]
ok, I updated the code, if you found something wrong, can you change it directly? Guess I could give you permission?

**Comment by shayki5** [comment]
@daxu7509 No problem :)

**Comment by ramyaramdasan** [comment]
Hi,

I am facing a similar issue and I am not sure if I understand this discussion to fix the issue. I have a Azure Pipeline on a GitHub repository and I am using this extension to create a Pull Request. This task gets executed each time the build pipeline runs, so except for the first build, this task throws a warning that 'A pull request already exists'. Though it is an expected behavior, I wonder if there is anyway this extension can update the PR incase one already exists. Please help!

**Comment by shayki5** [comment]
Hi @ramyaramdasan, this is another thing :)
Do you want if the PR is already so it will be updated?
Updated with what? title? description?

**Comment by ramyaramdasan** [comment]
Hi :) 

Yes, I know. The existing task is throwing an error/ warning which doesn't make my build statistics look good. 

Anyway, I have come across another extension which does both: https://marketplace.visualstudio.com/items?itemName=elranu.github-pr-tasks  

So, you can now ignore my ask :)

**Comment by shayki5** [comment]
Great 👍 Maybe I will ad it also to my extension :)

**Comment by ramyaramdasan** [comment]
Awesome! Please post if you do, I would be happy to add it to my pipeline 👍

**Comment by H0110WED** [comment]
Is there a date for when the by pass option will be implemented? We are also waiting for this feature.

**Comment by shayki5** [comment]
@H0110WED Do you use GitHub or Azure Repos?

**Comment by H0110WED** [comment]
@shayki5 We are using Azure devops

**Comment by shayki5** [comment]
@H0110WED Ok, so do you want to auto-complete the PR and bypass it even all policies didn't complete?

**Comment by H0110WED** [comment]
@shayki5 Correct. I messed with the azure devops rest apis a little and I'm not sure if you can bypass and auto-complete a PR though.

**Comment by Miigg** [comment]
Hello @ shayki5, I made a change to include the Bypass, I would like you to take a look, I don't know why but I had to do a retry to apply the bypass since the first attempt does not work.
PR #86

**Comment by shayki5** [comment]
@Miigg Thank you! I uploaded the new version with the Bypass option to production :)
@H0110WED @daxu7509  **FYI** ☝
