### ISSUE TITLE
Would like to do pull from tag and not branch

### ISSUE THREAD

**Issue by BrianHanf** [shayki5/azure-devops-create-pr-task#64]
Is there a way to create a pull from a tag (or commit for that matter) and not a branch?

**Comment by shayki5** [comment]
Hi @BrianHanf!

It's impossible due to git limitation. 
Pull Request it's between 2 branches.
If you want to merge a specific commit you can create a new branch with just that change:

```
$ git fetch --all
$ git checkout -b my-single-change upstream/master
$ git cherry-pick b50b2e7 (the sha1 of the commit)
$ git push -u origin my-single-change
```
Then create a PR from `my-single-change` to `master`.
