### ISSUE TITLE
Where is the extension?

### ISSUE THREAD

**Issue by deadlydog** [shayki5/azure-devops-create-pr-task#65]
I can't seem to find this extension in the Azure DevOps marketplace. A link to it in this repo's ReadMe would be super helpful. Maybe I'm missing it?

**Comment by deadlydog** [comment]
Ok, I found it by digging up the extension name out of the vss-extension.json file. It shouldn't be that hard though. Also, I'd recommend including `GitHub` as an extension tag to make it more discoverable.

**Comment by shayki5** [comment]
Hi @deadlydog 
When you search "create"  or "pull request" in the marketplace you can find it easily:
![image](https://user-images.githubusercontent.com/26063853/92923031-73bb6780-f43f-11ea-87fc-723f3eb68d77.png)

![image](https://user-images.githubusercontent.com/26063853/92923093-8b92eb80-f43f-11ea-9817-688f507fbbc4.png)

Anyway, I liked your changes and I merged your Pull Request :)
Thank you!!
Shayki
