### ISSUE TITLE
Pull Requests to another repository

### ISSUE THREAD

**Issue by Zucka** [shayki5/azure-devops-create-pr-task#67]
In one of the project I am working on, the team is using multiple repositories.
One of theese is the primary and a number of others are forks of that.
Whenever the primary is updated one of the team members is maunally creating pull requests for the individual forks.

Would it be possible to add functionality to target another repo instead of using the same as both source and target?

**Comment by shayki5** [comment]
Hi @Zucka!
It's a good idea!
I will start to work on it :)

**Comment by shayki5** [comment]
Hi @Zucka,

I implemented it in the new version :)
Just choose the forked repo and check the new checkbox `Is Forked Repository` or in YAML: `isForked: true`.

Best regards,
Shayki

**Comment by Zucka** [comment]
That's AWESOME !! 
Thank you!

/Johan
