### ISSUE TITLE
Auto Complete Pull Requests in GutHub

### ISSUE THREAD

**Issue by ramyaramdasan** [shayki5/azure-devops-create-pr-task#71]
Hi Shayki,

Thanks a lot for this extension, makes our work quite easy. We use GIT Repositories for source control. We are trying to incorporate all deployment tasks in the ADO pipeline, but using GitHub to approve/ merge pull request beats the purpose.  Do you have plans to extend the Auto Complete option to GIT Repositories also? Look forward to hearing your thoughts. 

Thanks
Ramya

**Comment by shayki5** [comment]
Hi Ramya,
I don't fully understand, your code is in GitHub or in ADO?
Currently the Auto Complete option is for ADO.

**Comment by ramyaramdasan** [comment]
Hi Shayki, 

My code is in GitHub, and I am curious if Auto Complete option would be added to GitHub, like you have for ADO today.

**Comment by shayki5** [comment]
There is such feature in GitHub?

**Comment by ramyaramdasan** [comment]
I am new to both GIT and ADO, I am exploring the possibilities. If there is no such option, is there a way to merge the pull request from ADO? I am a ServiceNow expert, we do have a plugin in ServiceNow using which we can merge a pull request in GitHub remotely by passing the required parameters.

**Comment by shayki5** [comment]
Oh ok, so you want to complete a PR from ADO? (because create a PR with auto complete is unavailable in GitHub)
Do you want to complete immediately after the PR is created? or wait to reviewers etc?

**Comment by ramyaramdasan** [comment]
At present, we are not looking at anyone reviewing the PR, so closing it immediately after creation works (wonder if that would run into issues in case of conflicts)

**Comment by shayki5** [comment]
@ramyaramdasan I will try to do it, need find a free time...

**Comment by ramyaramdasan** [comment]
Great! thanks a lot.

**Comment by SteffenMangold** [comment]
+1, needed feature
