### ISSUE TITLE
Unable to connect to azure repo

### ISSUE THREAD

**Issue by zycon** [shayki5/azure-devops-create-pr-task#72]
While running the task, throwing an error
2020-10-19T21:27:31.4787573Z Is Draft Pull Request: False
2020-10-19T21:27:31.4788275Z Auto-Complete: False
2020-10-19T21:27:31.4788905Z Link Work Items: True
2020-10-19T21:27:54.7772961Z ##[error]Unable to connect to the remote server
2020-10-19T21:27:55.6034783Z ##[section]Finishing: Code Merge Request for Stage/

** Agent is running behind a proxy? is that could be the issue,(btw agent is configured with proxy)

**Comment by zycon** [comment]
i think -Proxy needs to be passed for Invoke-RestMethod

**Comment by shayki5** [comment]
Hi @zycon, is it Azure DevOps Server (on-prem)? with self-hosted agent?

**Comment by zycon** [comment]
hi,
self-hosted windows

**Comment by shayki5** [comment]
Try login your machine and preform some `Invoke-RestMethod` functions with PowerShell, are you success? if not, with `-Proxy` is it works?

**Comment by zycon** [comment]
Hi,
Invoke-RestMethod works only with proxy in my scenario, it could be a nice feature if you can respect agent proxy configuration or an input from UI , i would love to contribute, but no-pre exp in ps and azure agents

**Comment by shayki5** [comment]
Can you tell me which parameters should passed as inputs?

**Comment by zycon** [comment]
Like an input from here
![image](https://user-images.githubusercontent.com/36449874/96615062-e1499600-1311-11eb-8b0c-419549595bc0.png)
or taking machines default proxy configuration

**Comment by shayki5** [comment]
I mean, in the `-Proxy` parameter you should give more info `-ProxyCredential` no? so what are the full parameters that should be?

**Comment by shayki5** [comment]
@zycon Did you see my above message?

**Comment by zycon** [comment]
That depends on the case, most of the case Proxy would be fine

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by shayki5** [comment]
@zycon Do you mean just to add `-Proxy`?

**Comment by shayki5** [comment]
@zycon ping :)

**Comment by zycon** [comment]
Yes. Would be better if you can add proxy definitions

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by shayki5** [comment]
Hi @zycon, do you still need it?
By the way, are you sure the proxy is the issue?

**Comment by shayki5** [comment]
Closed because no response.
