### ISSUE TITLE
Can't find field of "Allow scripts to access the OAuth token"

### ISSUE THREAD

**Issue by MahmoudBishr-IbnsinaPharma** [shayki5/azure-devops-create-pr-task#73]
I can't find "Allow scripts to access the OAuth token" field in PR task
When I start the pipeline the following error appear

![Screen Shot 2020-10-25 at 1 58 28 PM](https://user-images.githubusercontent.com/70334600/97106434-444c7b80-16ca-11eb-8106-c80ffa3c6a45.png)

**Comment by shayki5** [comment]
Hi @MahmoudBishr-IbnsinaPharma,
Is it YAML pipeline or via the UI?

**Comment by MahmoudBishr-IbnsinaPharma** [comment]
@shayki5 I'm using UI

**Comment by shayki5** [comment]
@MahmoudBishr-IbnsinaPharma Go to  the Agent job options, scroll down and check the checkbox "Allow scripts to access the OAuth token".

**Comment by MahmoudBishr-IbnsinaPharma** [comment]
I find it and it is working now with me. Thanks so much @shayki5
