### ISSUE TITLE
Plugin use in release pipelines

### ISSUE THREAD

**Issue by vinura** [shayki5/azure-devops-create-pr-task#76]
Even though the plugin works in the build pipeline, It doesn't work in release pipelines.  Is there any solution for this? [I get a git "contribute permission error" only when used with release pipelines]

{"$id":"1","innerException":null,"message":"TF401027: You need the Git 'PullRequestContribute' permission to perform this action. Details: identity 'Build\\###########################', scope 'repository'.","typeName":"Microsoft.TeamFoundation.Git.Server.GitNeedsPermissionException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitNeedsPermissionException","errorCode":0,"eventId":3000}

**Comment by shayki5** [comment]
Hi @vinura,
Can you check please issue #61?

**Comment by vinura** [comment]
Hey I tried adding project build service to build service accounts

![image](https://user-images.githubusercontent.com/11626591/98344651-8b772c80-2039-11eb-8726-886a9c322d04.png)


and ticked the repo level access of contribute and contribute pull service. 

![image](https://user-images.githubusercontent.com/11626591/98344784-c2e5d900-2039-11eb-80fe-a96e12985be0.png)

Still i get the same error. 

2020-11-06T08:30:07.9232726Z ##[error]{"$id":"1","innerException":null,"message":"TF401027: You need the Git 'PullRequestContribute' permission to perform this action. Details: identity 'Build\\ab398a4d-5368-45ee-b3bc-300c196293b5', scope 'repository'.","typeName":"Microsoft.TeamFoundation.Git.Server.GitNeedsPermissionException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitNeedsPermissionException","errorCode":0,"eventId":3000}

Any ideas would be really helpful.

**Comment by vinura** [comment]
I solved this by directly adding User -"Project Collection Build Service" to the repo as contribute and contribute pull request user. Thanks for the help <3

**Comment by vinura** [comment]
I am adding this for future reference for anyone 

There are two build services
as for my understanding, these utilized as follows

Azure pipelines use
User - <Project Name>Build Service <Org Name>

​
Release Pipeline uses
User -Project Collection Build Service

Adding these two services to repos in project level and ticking 

- [ ] contribute
- [ ] contribute to pull request

Will Solve all the issues

**Comment by shayki5** [comment]
Thank you @vinura for all the info!!
I glad it works for you :)
