### ISSUE TITLE
Pull Request failing with 405 Method not allowed

### ISSUE THREAD

**Issue by akinda** [shayki5/azure-devops-create-pr-task#78]
While running the task, I see an error and not sure why.
Image below with full error details

![Error-Pull-Request](https://user-images.githubusercontent.com/5349687/99252619-3d9eb900-27dd-11eb-8eb6-958db42b8fe8.png)

**Comment by shayki5** [comment]
Hi @akinda,
It looks like the PR is not created, did you gave permissions to the user?

**Comment by akinda** [comment]
@shayki5 

I gave permissions - Contribute (Allow) - to all users again just to be sure. 

The users/groups I gave the permissions to are below:

![image](https://user-images.githubusercontent.com/5349687/99265924-3f25ac80-27f0-11eb-9fd3-7c3fbb23a9a2.png)

![image](https://user-images.githubusercontent.com/5349687/99266054-5cf31180-27f0-11eb-9339-80a9b4cda813.png)

I'm seeing this now after enabling more debugging.

##[debug]<script type="text/javascript"> if (window.performance && window.performance.mark) { window.performance.mark('requireStart'); }
##[debug]require(["Authentication/Scripts/SPS.Authentication.Controls","Authentication/Scripts/SPS.Authentication"], function(){  if (window.performance && window.performance.mark) { window.performance.mark('requireEnd'); } window.requiredModulesLoaded=true;  });
##[debug]</script>
##[debug]
##[debug]</body>
##[debug]</html>
##[debug]
{
    "forkSource":  "",
    "sourceRefName":  "refs/heads/devel",
    "title":  "Auto-Merge latest devel into staging",
    "WorkItemRefs":  [
                         null
                     ],
    "description":  "Latest code",
    "reviewers":  "",
    "isDraft":  "False",
    "targetRefName":  "refs/heads/staging"
}
##[debug]POST https://askvet.visualstudio.com/Devon/_apis/git/repositories/Devon/pullrequests?api-version=5.0 with -1-byte payload
##[debug]received 15676-byte response of content type text/html; charset=utf-8
*************************
******** Success ********
*************************
Pull Request  created.
##[debug]{
##[debug]    "completionOptions":  {
##[debug]                              "mergeStrategy":  "Merge (No fast-forward)",
##[debug]                              "transitionWorkItems":  "False",
##[debug]                              "deleteSourceBranch":  "False",
##[debug]                              "mergeCommitMessage":  "Auto-Commit with latest dev updates"
##[debug]                          },
##[debug]    "autoCompleteSetBy":  {
##[debug]                              "id":  ""
##[debug]                          }
##[debug]}
##[debug]https://askvet.visualstudio.com/Devon/_apis/git/repositories/Devon/pullrequests/?api-version=5.0
##[debug]PATCH https://askvet.visualstudio.com/Devon/_apis/git/repositories/Devon/pullrequests/?api-version=5.0 with -1-byte payload
##[warning]Can't set Auto Complete to PR .
##[debug]Processed: ##vso[task.logissue type=warning]Can't set Auto Complete to PR .
##[warning]{"count":1,"value":{"Message":"The requested resource does not support http method 'PATCH'."}}
##[debug]Processed: ##vso[task.logissue type=warning]{"count":1,"value":{"Message":"The requested resource does not support http method 'PATCH'."}}
##[warning]The remote server returned an error: (405) Method Not Allowed.
##[debug]Processed: ##vso[task.logissue type=warning]The remote server returned an error: (405) Method Not Allowed.
##[debug]Leaving RunTask.
Finishing: Create Pull Request

**Comment by akinda** [comment]
Also even though it says Pull Request Created, I don't see anything in the Pull Requests 'Active' or 'Completed' page.

Is that typical?

![image](https://user-images.githubusercontent.com/5349687/99266703-0e924280-27f1-11eb-880c-16fde8a0e26c.png)

**Comment by shayki5** [comment]
@akinda Is not created the PR (even though it says Pull Request Created, if it was crated the PR ID will be there also).
Did you enable the access token?

**Comment by akinda** [comment]
@shayki5 That did the trick! 

Thanks!

Now, I feel bad because that was the very first thing in the directions but somehow I missed it.

Thanks again though! Everything seems to be seamlessly working now,

**Comment by shayki5** [comment]
@akinda Great! I glad it helped :)
