### ISSUE TITLE
Getting warnings  ( Pull request not merging to target branch)

### ISSUE THREAD

**Issue by raochandansingh** [shayki5/azure-devops-create-pr-task#79]
Hi,

I have tried to use this task in the pipeline of  Azure-DevOps. I can see the pull request is successfully created for the particular repo but it's not merging to the target branch. And these are the below warning I am getting. Could you please suggest to fix this issue.

![image](https://user-images.githubusercontent.com/48559155/104191037-d3b42180-53d1-11eb-81f9-a50c37dbfc5c.png)

**Comment by shayki5** [comment]
Hi @raochandansingh ,
You need to give to the user `Project Collection Build Service (account)` and `Build Service` permissions `Contribute to pull request` in the git repository, please see issue #28.

**Comment by raochandansingh** [comment]
Hi,

I have already given the permission for the above both users as 'Contribute to pull request. And the same user is using it to create the pull request. Could you please help? screenshots are below:- 

![image](https://user-images.githubusercontent.com/48559155/104206145-0ebf5080-53e4-11eb-8c58-39b7b9006caa.png)

![image](https://user-images.githubusercontent.com/48559155/104206329-3b736800-53e4-11eb-824e-db272dc01650.png)

**Comment by shayki5** [comment]
Did you grant the permissions also to "Core build service"?

**Comment by raochandansingh** [comment]
yes ,  I did

![image](https://user-images.githubusercontent.com/48559155/104208614-8a6dcd00-53e5-11eb-963d-d82f29a6baea.png)

**Comment by shayki5** [comment]
Oh now I see the issue (I think), you need to give also "Contribute" permissions, beside to "Contribute to pull request".

**Comment by raochandansingh** [comment]
yeah, now it's working fine. but this was not mentioned anywhere like Contribute permission is also required to perform the SetAutoComplete task.

I am so happy now :) Thanks a lot for your fastest response as I was struggling with this issue since last Friday.

**Comment by shayki5** [comment]
Great!! 
You're welcome!

**Comment by raochandansingh** [comment]
One last thing I want to ask, Is their a possibility to do this operation for multiple repos using a single task. e.g. I have 20 repos which have source and target branch name are same. So can we do it as a single task or I need to add 20 tasks for each repos in the pipeline

**Comment by shayki5** [comment]
Need 20 tasks :/  but it could be nice feature. I hope I will have time to add it.

**Comment by raochandansingh** [comment]
Okay, Thanks!!

**Comment by raochandansingh** [comment]
Hi, 

Could you please help why the belw error is coming.

**Comment by shayki5** [comment]
@raochandansingh Can you share your task configuration?
In addition, run the pipeline with `system.debug` = `true` and share the logs.

**Comment by raochandansingh** [comment]
I am trying to run two repos 

![image](https://user-images.githubusercontent.com/48559155/104447059-1ef43e80-5550-11eb-8d12-870219742093.png)



![image](https://user-images.githubusercontent.com/48559155/104446727-b9a04d80-554f-11eb-8aa2-65912aa252fd.png)

![image](https://user-images.githubusercontent.com/48559155/104446906-f1a79080-554f-11eb-9db2-6e496ad30988.png)

**Comment by shayki5** [comment]
Ok, I see it's a release pipeline. without reviews is it works? 
Do you use Azure DevOps or Azure DevOps Server?

**Comment by raochandansingh** [comment]
I am using Azur-DevOps. And Review is optional.

**Comment by shayki5** [comment]
Please see this comment: https://github.com/shayki5/azure-devops-create-pr-task/issues/76#issuecomment-722975169 maybe it will help.
Can you try to run it with `system.debug` = `true` and share here the full logs?
