### ISSUE TITLE
Add ability to add a group/team as a reviewer for Azure Devops

### ISSUE THREAD

**Issue by UnleashMayhem** [shayki5/azure-devops-create-pr-task#8]
Currently only users with an email can be added as a reviewer, which means it is currently not possible to add a group as a reviewer. 

This is important to have as a way to assign a team to a PR without adding each user individually.

**Comment by shayki5** [comment]
Hi @UnleashMayhem,

This is a great idea!
I will start work on it :)

Kind regards,
Shayki

**Comment by shayki5** [comment]
Hi again @UnleashMayhem :)

I added this feature in the new version - 1.2.30
You can add a team with the team name and also combine with users, for example:
`Team name1;Team name 2;myemail@gmail.com`

Kind regards,
Shayki
