### ISSUE TITLE
Typo in ‘deleteSourch’ input option (sould be ‘deleteSource’?)?

### ISSUE THREAD

**Issue by kachkaev** [shayki5/azure-devops-create-pr-task#80]
When reading the docs on https://marketplace.visualstudio.com/items?itemName=ShaykiAbramczyk.CreatePullRequest, I noticed a typo in ‘delete source branch’ option (deleteSourch) and fixed it locally in my yaml. 

However, after it did not work, I realised that the typo is not just in the docs, but also in the code:
https://github.com/shayki5/azure-devops-create-pr-task/search?q=deleteSourch

> ![Screenshot 2021-01-15 at 10 31 00](https://user-images.githubusercontent.com/608862/104714308-f8373300-571c-11eb-873a-60a5514e9791.png)

I wonder if it would be possible to fix the typo in the docs and in the code, while keeping the old option for backwards compatibility. WDYT?

**Comment by shayki5** [comment]
Hi @kachkaev,
Great catch, I don't understand how I missed it...
Good question, I think I can add a new field `deleteSource`, keep also the old field and in the code handle it.
I will try to do it next week.

**Comment by shayki5** [comment]
@kachkaev Still didn't have time to it... It's more complicated because in the UI will be two fields. maybe I will update the version to 2.0

**Comment by shayki5** [comment]
@kachkaev fixed :)
