### ISSUE TITLE
Suddenly the task started failing with the error: "##[error]The remote server returned an error: (404) Not Found."

### ISSUE THREAD

**Issue by DmytroSly** [shayki5/azure-devops-create-pr-task#82]
Although I didn't change anything related to the task, it started failing with the error:

"##[error]The remote server returned an error: (404) Not Found."

![image](https://user-images.githubusercontent.com/71351803/105725426-9ef7ac80-5f31-11eb-97bd-7f56832f8c02.png)

**Comment by shayki5** [comment]
Hi @DmytroSly,
Can you run it with `system.debug` = `true` and share the full log?

**Comment by DmytroSly** [comment]
Hi @shayki5 .
` system.debug = true` was a great help. The reason for the error was that the source branch name contained '&'.

**Comment by shayki5** [comment]
Great :)
