### ISSUE TITLE
Issue with By Pass policy and LastMergeSourceCommit

### ISSUE THREAD

**Issue by Youru** [shayki5/azure-devops-create-pr-task#89]
Hi, 

We recently added your plugin on azure dev ops to manage the autocomplete of some branches and even if there are some bug (or some lack of understanding on our side) the plugin works well, so good job. 

I encounter this morning an issue with the by pass policy (The PR is sucessfully created) 
Error message : 
##[warning]Can't Bypass PR 253.
##[warning]{"$id":"1","innerException":null,"message":"Invalid argument value.\r\nParameter name: You must specify a valid LastMergeSourceCommit to perform this operation.","typeName":"Microsoft.TeamFoundation.SourceControl.WebServer.InvalidArgumentValueException, Microsoft.TeamFoundation.SourceControl.WebServer","typeKey":"InvalidArgumentValueException","errorCode":0,"eventId":0}
##[warning]The remote server returned an error: (400) Bad Request.

Do you know what configuration I missed or if I need to add a specific security permission to my agent group? 
![configuration](https://user-images.githubusercontent.com/1332200/109282179-79560f80-781d-11eb-8d2a-2f39e0849ee6.jpg)

Thanks

Edit : Ps : 
The following sentence has already been done from our side
If you want to use Bypass you need to give also the permisison "Bypass policies when completing pull requests"

**Comment by Youru** [comment]
I've saw the code and I think I know by which part the issue came.
It seems that we need to check Link work item to set $global:lastCommitId. 

Others issues are coming from the UI, when we select specifics options like set auto complete, other field are hidden. (but we can play with the persistance of the choice) 

Now I've a new error message with 
You need the Git 'GenericContribute' permission

I'll add it to the agent group and I'll come back I if see something else

**Comment by shayki5** [comment]
Hi @Youru, thank you for your info!
So, for conclusion - for the ByPass the work items must be linked? and need to give ByPass and GenericContribute  permissions to the user?

**Comment by Youru** [comment]
Short answer : 
Yes 

Long :
line 321 - 324
We call  GetLinkedWorkItems  onfy if linkWorkItems if true

Line 619 -620 
$global:lastCommitId and $global:lastCommitUrl are set

Line 709-710
$global:lastCommitId and $global:lastCommitUrl are used 

Do this part should be extracted from GetLinkedWorkItems  method ?

**Comment by shayki5** [comment]
@Miigg can you answer the question above?

**Comment by Miigg** [comment]
> @Miigg can you answer the question above?

@shayki5 and @Youru I did a validation for this vars and if they have no value I will try to obtain and define the values 
#91

**Comment by shayki5** [comment]
@Miigg Good work! but now still the ByPass will work only if "link work items" is true. can you get the commits inside the ByPass function....?

**Comment by Miigg** [comment]
> @Miigg Good work! but now still the ByPass will work only if "link work items" is true. can you get the commits inside the ByPass function....?

@shayki5 In the tests I did here always with the "link work items" disabled and it worked normally, can you test it again?

**Comment by shayki5** [comment]
@Miigg I checked now it it worked... but I don't know why, the bypass need the last commit id & url and we get them only in the `GetLinkedWorkItems` function...

**Comment by shayki5** [comment]
@Miigg Now I see you added the lastCommitId variables also in the ByPassPR function (to get it from Get-PRData function). so, we don't need it in the GetLinkedWorkItems function, because of issue #92 I removed it from there, I guess it's related to the error.
