### ISSUE TITLE
 ##[error]Cannot index into a null array.

### ISSUE THREAD

**Issue by danielheddelin** [shayki5/azure-devops-create-pr-task#92]
On feb 15, our production release pipeline worked (version 1.2.198).
Our next release on march 2, did not work (1.2.209).

The create PR task is failing with  ##[error]Cannot index into a null array.

The version used is 1.2.209, which is not even in the version list, so maybe it was released prematurely?

**Comment by shayki5** [comment]
Hi @danielheddelin, thanks for reporting that!
We added a bypass feature and I think I know what is the issue, I fixed it, can you try now?

**Comment by danielheddelin** [comment]
Thanks for the response. I will let you know the results of our next deploy.

**Comment by danielheddelin** [comment]
Case closed. Cannot index into a null array has been solved.
Ended up with another error and have now followed your guide on this, so expecting everything to work as intended after this. Thank you. 
##[error]Access Token doesn't found! please enable the access token in your pipeline. see the docs: https://github.com/shayki5/azure-devops-create-pr-task

**Comment by shayki5** [comment]
@danielheddelin Great! I just added the message regarding the token :) I happy it helped you.
