### ISSUE TITLE
Ability to create a PR using the SHA?

### ISSUE THREAD

**Issue by mikecole** [shayki5/azure-devops-create-pr-task#95]
From the documentation it appears the PR is from the latest version of the source branch. Is there any way to target a specific commit? By the time my workflow can get to this job it's possible more commits have been made to the branch, so I'm really looking for this to do a point-in-time PR if that is possible. Thanks!

**Comment by shayki5** [comment]
Hi @mikecole, it's impossible, PR is a merge from branch to branch. if you want only specific commits to be merged you can [cherry pick ](https://docs.microsoft.com/en-us/azure/devops/repos/git/cherry-pick?view=azure-devops&tabs=visual-studio)them to a new branch, then create the PR from there.
