### ISSUE TITLE
Get back the IDs in case of multiple branches at once

### ISSUE THREAD

**Issue by orty** [shayki5/azure-devops-create-pr-task#97]
Hi,

Very nice work you did with this custom task, thanks a lot ! 

I would like to be able to get back the list of `pullRequestId` (probably using a separator like ";") as an output variable even in the case of a multiple branch run.
If you lack the time to update your task and the idea is still interesting for you, may I propose a PR on your repo ?

Thanks again

**Comment by shayki5** [comment]
Hi @orty,

I'm glad to hear it's helpful to you :)

I can try to add it, but I don't know if it will be soon :/

If you have time to propose a PR it could be great!

**Comment by orty** [comment]
Hi @shayki5,

I developped and tried the fix on my Azure Devops environment. I just can't push any new branch (hence can't create a PR :)) for it.

May you allow me to do so ? I shall respect your naming convention of course, and name the new branch `feature/multiple-output-pullrequestids`.

Please, let me know if you agree, I just have to click on 'push' ^^.

**Comment by orty** [comment]
#98

**Comment by orty** [comment]
Just created the PR #98 @shayki5

**Comment by shayki5** [comment]
Hi @orty!
I tested your change in my environment and it works great!
I approved the PR and and a new version will be ready soon for update :)
Thank you for your effort!

**Comment by orty** [comment]
You're very welcome :)

**Comment by shayki5** [comment]
The new version (1.2.225) is uploaded :)
